//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cb1
// {
//
//   float4 cb1[123];                   // Offset:    0 Size:  1968
//
// }
//
// cbuffer cb0
// {
//
//   float4 cb0[19];                    // Offset:    0 Size:   304
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// t0                                texture  float4          2d             t0      1 
// t1                                texture  float4          2d             t1      1 
// t2                                texture  float4          2d             t2      1 
// cb0                               cbuffer      NA          NA            cb0      1 
// cb1                               cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float       
// SV_Position              0   xyzw        1      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB1[123], immediateIndexed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps_siv linear noperspective v1.xy, position
dcl_output o0.xyzw
dcl_temps 14
round_ni r0.xy, v1.xyxx
dp2 r0.z, r0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
frc r0.z, r0.z
mul r0.z, r0.z, l(52.982918)
frc r1.xz, r0.zzzz
add r2.xyzw, r0.xyxy, l(32.665001, 11.815000, 0.500000, 0.500000)
dp2 r0.z, r2.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
frc r0.z, r0.z
mul r0.z, r0.z, l(52.982918)
frc r1.yw, r0.zzzz
mad r0.zw, r1.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000), l(0.000000, 0.000000, -0.250000, -0.250000)
add r2.xy, r2.zwzz, -cb1[121].xyxx
mad r0.zw, r2.xxxy, l(0.000000, 0.000000, 0.062500, 0.062500), r0.zzzw
round_ni r0.zw, r0.zzzw
add r2.xy, cb1[122].xyxx, l(15.000000, 15.000000, 0.000000, 0.000000)
mul r2.xy, r2.xyxx, l(0.062500, 0.062500, 0.000000, 0.000000)
round_z r2.xy, r2.xyxx
ftoi r0.zw, r0.zzzw
imax r0.zw, r0.zzzw, l(0, 0, 0, 0)
ftoi r2.xy, r2.xyxx
imin r3.xy, r0.zwzz, r2.xyxx
mov r3.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r3.xyzw, r3.xyzw, t2.xyzw
mul r4.xyzw, r3.zwzw, cb0[18].yyyy
dp2 r0.z, r4.zwzz, r4.zwzz
ftoi r5.xy, r0.xyxx
mov r5.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.xyw, r5.xyww, t0.xywz
lt r2.x, r0.z, l(0.250000)
if_z r2.x
  mul r2.xy, r3.xyxx, cb0[18].yyyy
  dp2 r2.x, r2.xyxx, r2.xyxx
  add r3.xyzw, cb1[121].xyxy, cb1[122].xyxy
  add r3.xyzw, r3.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
  round_z r6.xyzw, cb1[121].xyxy
  round_z r3.xyzw, r3.xyzw
  mul r2.y, r0.z, l(0.500000)
  lt r2.x, r2.y, r2.x
  if_nz r2.x
    add r7.xyzw, -r1.zwzw, l(1.000000, 1.000000, 2.000000, 2.000000)
    mul r7.xyzw, r7.xyzw, l(0.025000, 0.025000, 0.025000, 0.025000)
    mad r8.xyzw, r7.xxzz, r4.zwzw, r2.zwzw
    round_ni r8.xyzw, r8.xyzw
    ftoi r8.xyzw, r8.xyzw
    ftoi r9.xyzw, r6.zwzw
    imax r8.xyzw, r8.xyzw, r9.xyzw
    ftoi r10.xyzw, r3.zwzw
    imin r8.xyzw, r8.zwxy, r10.zwxy
    mad r7.xyzw, -r7.yyww, r4.xyzw, r2.zwzw
    round_ni r7.xyzw, r7.xyzw
    ftoi r7.xyzw, r7.xyzw
    imax r7.xyzw, r9.xyzw, r7.xyzw
    imin r7.xyzw, r10.zwxy, r7.zwxy
    mov r11.xy, r8.zwzz
    mov r11.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r11.xyz, r11.xyzw, t0.xyzw
    mov r12.xy, r7.zwzz
    mov r12.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r12.xyz, r12.xyzw, t0.xyzw
    add r11.xyz, r11.xyzx, r12.xyzx
    mov r8.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r8.xyz, r8.xyzw, t0.xyzw
    add r8.xyz, r11.xyzx, r8.xyzx
    mov r7.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r7.xyz, r7.xyzw, t0.xyzw
    add r7.xyz, r7.xyzx, r8.xyzx
    add r8.xyzw, -r1.zwzw, l(3.000000, 3.000000, 4.000000, 4.000000)
    mul r8.xyzw, r8.xyzw, l(0.025000, 0.025000, 0.025000, 0.025000)
    mad r11.xyzw, r8.xxzz, r4.zwzw, r2.zwzw
    round_ni r11.xyzw, r11.xyzw
    ftoi r11.xyzw, r11.xyzw
    imax r11.xyzw, r9.xyzw, r11.xyzw
    imin r11.xyzw, r10.zwxy, r11.zwxy
    mad r8.xyzw, -r8.yyww, r4.xyzw, r2.zwzw
    round_ni r8.xyzw, r8.xyzw
    ftoi r8.xyzw, r8.xyzw
    imax r8.xyzw, r9.xyzw, r8.xyzw
    imin r8.xyzw, r10.zwxy, r8.zwxy
    mov r9.xy, r11.zwzz
    mov r9.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r9.xyz, r9.xyzw, t0.xyzw
    add r7.xyz, r7.xyzx, r9.xyzx
    mov r9.xy, r8.zwzz
    mov r9.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r9.xyz, r9.xyzw, t0.xyzw
    add r7.xyz, r7.xyzx, r9.xyzx
    mov r11.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r9.xyz, r11.xyzw, t0.xyzw
    add r7.xyz, r7.xyzx, r9.xyzx
    mov r8.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r8.xyz, r8.xyzw, t0.xyzw
    add r7.xyz, r7.xyzx, r8.xyzx
    mul r0.xyw, r7.xyxz, l(0.125000, 0.125000, 0.000000, 0.125000)
  else 
    rsq r0.z, r0.z
    mul r0.z, r0.z, l(4.000000)
    ld_indexable(texture2d)(float,float,float,float) r2.xy, r5.xyzw, t1.xyzw
    mul r2.x, r2.x, cb0[18].y
    min r5.y, r2.x, cb0[18].w
    add r7.xyzw, -r1.zwzw, l(1.000000, 1.000000, 2.000000, 2.000000)
    mul r8.xyzw, r7.xyzw, l(0.025000, 0.025000, 0.025000, 0.025000)
    mad r9.xyzw, r8.xxzz, r4.zwzw, r2.zwzw
    round_ni r9.xyzw, r9.xyzw
    ftoi r9.xyzw, r9.xyzw
    ftoi r6.xyzw, r6.xyzw
    imax r9.xyzw, r6.xyzw, r9.xyzw
    ftoi r3.xyzw, r3.xyzw
    imin r9.xyzw, r3.zwxy, r9.zwxy
    mad r8.xyzw, -r8.yyww, r4.xyzw, r2.zwzw
    round_ni r8.xyzw, r8.xyzw
    ftoi r8.xyzw, r8.xyzw
    imax r8.xyzw, r6.xyzw, r8.xyzw
    imin r8.xyzw, r3.zwxy, r8.zwxy
    mov r10.xy, r9.zwzz
    mov r10.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r7.yw, r10.xyww, t1.zxwy
    ld_indexable(texture2d)(float,float,float,float) r10.xyz, r10.xyzw, t0.xyzw
    mul r2.x, r7.y, cb0[18].y
    min r5.x, r2.x, cb0[18].w
    add r2.x, -r2.y, r7.w
    mad_sat r11.xy, r2.xxxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    mul_sat r11.zw, r0.zzzz, r5.yyyx
    dp2 r2.x, r11.xyxx, r11.zwzz
    mov r11.xy, r8.zwzz
    mov r11.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r12.xy, r11.xyww, t1.xyzw
    ld_indexable(texture2d)(float,float,float,float) r11.xyz, r11.xyzw, t0.xyzw
    mul r7.y, r12.x, cb0[18].y
    min r5.z, r7.y, cb0[18].w
    add r7.y, -r2.y, r12.y
    mad_sat r12.xz, r7.yyyy, l(1.000000, 0.000000, -1.000000, 0.000000), l(0.500000, 0.000000, 0.500000, 0.000000)
    mul_sat r13.xy, r0.zzzz, r5.yzyy
    dp2 r7.y, r12.xzxx, r13.xyxx
    lt r7.w, r12.y, r7.w
    and r10.w, r7.w, l(0xbf800000)
    lt r11.w, r5.x, r5.z
    and r10.w, r10.w, r11.w
    ne r10.w, l(0.000000, 0.000000, 0.000000, 0.000000), r10.w
    movc r10.w, r10.w, r7.y, r2.x
    or r7.w, r7.w, r11.w
    itof r7.w, r7.w
    ne r7.w, l(0.000000, 0.000000, 0.000000, 0.000000), r7.w
    movc r2.x, r7.w, r7.y, r2.x
    mul r11.xyz, r11.xyzx, r2.xxxx
    mad r10.xyz, r10.wwww, r10.xyzx, r11.xyzx
    add r2.x, r2.x, r10.w
    mov r9.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r7.yw, r9.xyww, t1.zxwy
    ld_indexable(texture2d)(float,float,float,float) r9.xyz, r9.xyzw, t0.xyzw
    mul r7.y, r7.y, cb0[18].y
    min r5.w, r7.y, cb0[18].w
    add r7.y, -r2.y, r7.w
    mad_sat r11.xy, r7.yyyy, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    mad_sat r11.zw, r0.zzzz, r5.yyyw, -r7.xxxx
    dp2 r7.y, r11.xyxx, r11.zwzz
    mov r8.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r11.xy, r8.xyww, t1.xyzw
    ld_indexable(texture2d)(float,float,float,float) r8.xyz, r8.xyzw, t0.xyzw
    mul r8.w, r11.x, cb0[18].y
    min r5.x, r8.w, cb0[18].w
    add r8.w, -r2.y, r11.y
    mad_sat r11.xz, r8.wwww, l(1.000000, 0.000000, -1.000000, 0.000000), l(0.500000, 0.000000, 0.500000, 0.000000)
    mad_sat r12.xy, r0.zzzz, r5.yxyy, -r7.xxxx
    dp2 r7.x, r11.xzxx, r12.xyxx
    lt r7.w, r11.y, r7.w
    and r8.w, r7.w, l(0xbf800000)
    lt r9.w, r5.w, r5.x
    and r8.w, r8.w, r9.w
    ne r8.w, l(0.000000, 0.000000, 0.000000, 0.000000), r8.w
    movc r8.w, r8.w, r7.x, r7.y
    or r7.w, r7.w, r9.w
    itof r7.w, r7.w
    ne r7.w, l(0.000000, 0.000000, 0.000000, 0.000000), r7.w
    movc r7.x, r7.w, r7.x, r7.y
    mad r9.xyz, r8.wwww, r9.xyzx, r10.xyzx
    mad r8.xyz, r7.xxxx, r8.xyzx, r9.xyzx
    add r2.x, r2.x, r8.w
    add r2.x, r7.x, r2.x
    add r1.xyzw, -r1.xyzw, l(3.000000, 3.000000, 4.000000, 4.000000)
    mul r9.xyzw, r1.xyzw, l(0.025000, 0.025000, 0.025000, 0.025000)
    mad r10.xyzw, r9.xxzz, r4.zwzw, r2.zwzw
    round_ni r10.xyzw, r10.xyzw
    ftoi r10.xyzw, r10.xyzw
    imax r10.xyzw, r6.xyzw, r10.xyzw
    imin r10.xyzw, r3.zwxy, r10.zwxy
    mad r4.xyzw, -r9.yyww, r4.xyzw, r2.zwzw
    round_ni r4.xyzw, r4.xyzw
    ftoi r4.xyzw, r4.xyzw
    imax r4.xyzw, r6.xyzw, r4.xyzw
    imin r3.xyzw, r3.zwxy, r4.zwxy
    mov r4.xy, r10.zwzz
    mov r4.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r1.yz, r4.xyww, t1.zxyw
    ld_indexable(texture2d)(float,float,float,float) r4.xyz, r4.xyzw, t0.xyzw
    mul r1.y, r1.y, cb0[18].y
    min r5.z, r1.y, cb0[18].w
    add r1.y, -r2.y, r1.z
    mad_sat r1.yw, r1.yyyy, l(0.000000, 1.000000, 0.000000, -1.000000), l(0.000000, 0.500000, 0.000000, 0.500000)
    mad_sat r2.zw, r0.zzzz, r5.yyyz, -r7.zzzz
    dp2 r1.y, r1.ywyy, r2.zwzz
    mov r6.xy, r3.zwzz
    mov r6.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r2.zw, r6.xyww, t1.zwxy
    ld_indexable(texture2d)(float,float,float,float) r6.xyz, r6.xyzw, t0.xyzw
    mul r1.w, r2.z, cb0[18].y
    min r5.w, r1.w, cb0[18].w
    add r1.w, -r2.y, r2.w
    mad_sat r7.xy, r1.wwww, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    mad_sat r7.zw, r0.zzzz, r5.yyyw, -r7.zzzz
    dp2 r1.w, r7.xyxx, r7.zwzz
    lt r1.z, r2.w, r1.z
    lt r2.z, r5.z, r5.w
    and r2.w, r1.z, r2.z
    movc r2.w, r2.w, r1.w, r1.y
    or r1.z, r1.z, r2.z
    itof r1.z, r1.z
    ne r1.z, l(0.000000, 0.000000, 0.000000, 0.000000), r1.z
    movc r1.y, r1.z, r1.w, r1.y
    mad r4.xyz, r2.wwww, r4.xyzx, r8.xyzx
    mad r4.xyz, r1.yyyy, r6.xyzx, r4.xyzx
    add r1.z, r2.x, r2.w
    add r1.y, r1.y, r1.z
    mov r10.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r1.zw, r10.xyww, t1.zwxy
    ld_indexable(texture2d)(float,float,float,float) r2.xzw, r10.xyzw, t0.xwyz
    mul r1.z, r1.z, cb0[18].y
    min r5.x, r1.z, cb0[18].w
    add r1.z, -r2.y, r1.w
    mad_sat r6.xy, r1.zzzz, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    mad_sat r6.zw, r0.zzzz, r5.yyyx, -r1.xxxx
    dp2 r1.z, r6.xyxx, r6.zwzz
    mov r3.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r6.xy, r3.xyww, t1.xyzw
    ld_indexable(texture2d)(float,float,float,float) r3.xyz, r3.xyzw, t0.xyzw
    mul r3.w, r6.x, cb0[18].y
    min r5.z, r3.w, cb0[18].w
    add r2.y, -r2.y, r6.y
    mad_sat r6.xz, r2.yyyy, l(1.000000, 0.000000, -1.000000, 0.000000), l(0.500000, 0.000000, 0.500000, 0.000000)
    mad_sat r5.yw, r0.zzzz, r5.yyyz, -r1.xxxx
    dp2 r0.z, r6.xzxx, r5.ywyy
    lt r1.x, r6.y, r1.w
    lt r1.w, r5.x, r5.z
    and r2.y, r1.x, r1.w
    movc r2.y, r2.y, r0.z, r1.z
    or r1.x, r1.w, r1.x
    itof r1.x, r1.x
    ne r1.x, l(0.000000, 0.000000, 0.000000, 0.000000), r1.x
    movc r0.z, r1.x, r0.z, r1.z
    mad r1.xzw, r2.yyyy, r2.xxzw, r4.xxyz
    mad r1.xzw, r0.zzzz, r3.xxyz, r1.xxzw
    add r1.y, r1.y, r2.y
    add r0.z, r0.z, r1.y
    mad r0.z, r0.z, l(-0.125000), l(1.000000)
    max r0.z, r0.z, l(0.000000)
    mul r1.xyz, r1.xzwx, l(0.125000, 0.125000, 0.125000, 0.000000)
    mad r0.xyw, r0.zzzz, r0.xyxw, r1.xyxz
  endif 
endif 
dp3 o0.xyz, r0.xywx, l(0.212600, 0.715200, 0.072200, 0.000000)
mov o0.w, l(0)
ret 
// Approximately 261 instruction slots used
