//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.9 on Mon Aug 31 08:54:06 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[5], immediateIndexed
dcl_constantbuffer CB1[140], immediateIndexed
dcl_constantbuffer CB2[1280], dynamicIndexed
dcl_constantbuffer CB3[1024], dynamicIndexed
dcl_constantbuffer CB4[768], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2darray (float,float,float,float) t9
dcl_resource_buffer (uint,uint,uint,uint) t10
dcl_resource_structured t11, 80
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.xy
dcl_temps 29
dcl_thread_group 16, 16, 1
iadd r0.x, vThreadGroupID.x, l(0x00010e00)
ld_indexable(buffer)(uint,uint,uint,uint) r0.x, r0.xxxx, t10.xyzw
and r1.x, r0.x, l(255)
ushr r1.y, r0.x, l(8)
imad r0.yz, r1.xxyx, l(0, 16, 16, 0), vThreadIDInGroup.xxyx
iadd r1.xy, r0.yzyy, cb0[1].xyxx
ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r0.w, r0.x, l(0), t11.xxxx
ine r2.x, cb0[4].y, l(0)
ult r2.y, l(64), r0.w
and r2.x, r2.y, r2.x
if_nz r2.x
  store_uav_typed u0.xyzw, r1.xyyy, l(2.000000,0,0,1.000000)
  ret
endif
utof r0.yz, r0.yyzy
add r0.yz, r0.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
iadd r2.xy, -cb0[1].xyxx, cb0[1].zwzz
utof r2.xy, r2.xyxx
div r0.yz, r0.yyzy, r2.xxyx
mad r0.yz, r0.yyzy, l(0.000000, 2.000000, -2.000000, 0.000000), l(0.000000, -1.000000, 1.000000, 0.000000)
mov r1.z, l(0)
ld_indexable(texture2d)(float,float,float,float) r2.x, r1.xyzz, t4.xyzw
mad r2.y, r2.x, cb1[57].x, cb1[57].y
mad r2.x, r2.x, cb1[57].z, -cb1[57].w
rcp r2.x, r2.x
add r2.x, r2.x, r2.y
mul r0.yz, r0.yyzy, r2.xxxx
mul r3.xyzw, r0.zzzz, cb1[41].xyzw
mad r3.xyzw, r0.yyyy, cb1[40].xyzw, r3.xyzw
mad r3.xyzw, r2.xxxx, cb1[42].xyzw, r3.xyzw
add r3.xyzw, r3.xyzw, cb1[43].xyzw
div r2.yzw, r3.xxyz, r3.wwww
umin r0.w, r0.w, l(64)
ld_indexable(texture2d)(float,float,float,float) r3.xyz, r1.xyzz, t1.xyzw
ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.xyzz, t2.xyzw
ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r1.xyzz, t3.xyzw
mad r3.xyz, r3.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
dp3 r3.w, r3.xyzx, r3.xyzx
rsq r3.w, r3.w
mul r3.xyz, r3.wwww, r3.xyzx
mad r3.w, r4.w, l(255.000000), l(0.500000)
ftou r3.w, r3.w
and r6.xy, r3.wwww, l(15, 16, 0, 0)
add r3.w, -r4.x, l(1.000000)
mul r7.xyz, r5.xyzx, r3.wwww
mul r4.yw, r4.yyyz, r4.yyyz
mul r6.z, r4.y, l(0.160000)
mad r5.xyz, -r4.yyyy, l(0.160000, 0.160000, 0.160000, 0.000000), r5.xyzx
mad r5.xyz, r4.xxxx, r5.xyzx, r6.zzzz
mad r7.xyz, r7.xyzx, cb1[132].wwww, cb1[132].xyzx
ieq r8.xyzw, r6.xxxx, l(1, 2, 5, 3)
or r4.xy, r8.yzyy, r8.xxxx
mad r6.xzw, r5.xxyz, cb1[133].wwww, cb1[133].xxyz
movc r5.xyz, r4.xxxx, r6.xzwx, r5.xyzx
mad r6.xzw, r5.xxyz, l(0.450000, 0.000000, 0.450000, 0.450000), r7.xxyz
movc r7.xyz, r6.yyyy, r3.wwww, r7.xyzx
utof r8.xy, r1.xyxx
add r8.xy, r8.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mul r8.xy, r8.xyxx, cb1[126].zwzz
sample_l_indexable(texture2d)(float,float,float,float) r3.w, r8.xyxx, t5.yzwx, s0, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r4.x, r8.xyxx, t6.yxzw, s1, l(0.000000)
add r8.xyz, -r2.yzwy, cb1[59].xyzx
dp3 r6.y, r8.xyzx, r8.xyzx
rsq r6.y, r6.y
mul r8.xyz, r6.yyyy, r8.xyzx
ishl r1.w, cb1[139].z, l(3)
and r9.xyz, r1.xywx, l(63, 63, 63, 0)
mov r9.w, l(0)
ld_indexable(texture3d)(float,float,float,float) r9.xy, r9.xyzw, t0.xyzw
mad r9.xy, r9.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
lt r9.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r9.xxxy
lt r10.xy, r9.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
iadd r9.zw, -r9.zzzw, r10.xxxy
itof r9.zw, r9.zzzw
add r9.xy, -|r9.xyxx|, l(1.000000, 1.000000, 0.000000, 0.000000)
sqrt r9.xy, r9.xyxx
add r9.xy, -r9.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r9.xy, r9.xyxx, r9.zwzz
mul r9.xy, r9.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000)
mov r1.w, l(0)
mov r6.y, l(0)
mov r7.w, l(0)
mov r9.zw, l(0,0,0,0)
mov r10.x, l(0)
loop
  ult r10.y, r9.z, r0.w
  ult r10.z, r10.x, l(8)
  and r10.y, r10.z, r10.y
  breakc_z r10.y
  and r10.y, r9.z, l(-4)
  iadd r10.y, r10.y, l(16)
  ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r10.y, r0.x, r10.y, t11.xxxx
  bfi r10.z, l(2), l(3), r9.z, l(0)
  ushr r10.y, r10.y, r10.z
  and r10.z, r10.y, l(255)
  ge r10.w, cb2[r10.z + 0].x, l(0.000000)
  if_nz r10.w
    bfi r10.y, l(8), l(2), r10.y, l(0)
    mul r11.xyzw, r0.zzzz, cb2[r10.y + 257].xyzw
    mad r11.xyzw, r0.yyyy, cb2[r10.y + 256].xyzw, r11.xyzw
    mad r11.xyzw, r2.xxxx, cb2[r10.y + 258].xyzw, r11.xyzw
    add r11.xyzw, r11.xyzw, cb2[r10.y + 259].xyzw
    rcp r10.y, r11.w
    mul r10.yw, r10.yyyy, r11.xxxy
    add r11.x, l(1.000000), -cb2[r10.z + 0].w
    max r11.x, r11.x, l(0.000000)
    mul r11.xy, r9.xyxx, r11.xxxx
    mad r10.yw, r10.yyyw, cb0[3].xxxy, r11.xxxy
    add r10.yw, r10.yyyw, l(0.000000, -0.500000, 0.000000, -0.500000)
    round_z r11.xy, r10.ywyy
    add r10.yw, r10.yyyw, -r11.xxxy
    add r11.xy, r11.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
    mul r12.xy, r11.xyxx, cb0[3].zwzz
    mov r12.z, cb2[r10.z + 0].x
    gather4_aoffimmi_indexable(-1,-1,0)(texture2darray)(float,float,float,float) r13.xyzw, r12.xyzx, t9.xyzw, s3.x
    add r14.xyzw, -r11.zzzz, r13.xyzw
    mad_sat r14.xyzw, r14.xyzw, cb2[r10.z + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r13.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r13.xyzw
    and r13.xyzw, r13.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r13.xyzw, r13.xyzw, r14.xyzw
    min r13.xyzw, r13.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(1,-1,0)(texture2darray)(float,float,float,float) r14.xyzw, r12.xyzx, t9.xyzw, s3.x
    add r15.xyzw, -r11.zzzz, r14.xyzw
    mad_sat r15.xyzw, r15.xyzw, cb2[r10.z + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r14.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r14.xyzw
    and r14.xyzw, r14.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r14.xyzw, r14.xyzw, r15.xyzw
    min r14.xyzw, r14.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(-1,1,0)(texture2darray)(float,float,float,float) r15.xyzw, r12.xyzx, t9.xyzw, s3.x
    add r16.xyzw, -r11.zzzz, r15.xyzw
    mad_sat r16.xyzw, r16.xyzw, cb2[r10.z + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r15.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r15.xyzw
    and r15.xyzw, r15.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r15.xyzw, r15.xyzw, r16.xyzw
    min r15.xyzw, r15.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(1,1,0)(texture2darray)(float,float,float,float) r12.xyzw, r12.xyzx, t9.xyzw, s3.x
    add r11.xyzw, -r11.zzzz, r12.xyzw
    mad_sat r11.xyzw, r11.xyzw, cb2[r10.z + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r12.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r12.xyzw
    and r12.xyzw, r12.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r11.xyzw, r11.xyzw, r12.xyzw
    min r11.xyzw, r11.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    add r12.xy, -r13.wxww, r14.zyzz
    mad r12.xy, r10.yyyy, r12.xyxx, r13.wxww
    add r12.xy, r13.zyzz, r12.xyxx
    add r12.xy, r14.wxww, r12.xyxx
    add r11.yz, -r15.wwxw, r11.zzyz
    mad r11.yz, r10.yyyy, r11.yyzy, r15.wwxw
    add r11.yz, r15.zzyz, r11.yyzy
    add r11.xy, r11.wxww, r11.yzyy
    add r10.y, -r12.x, r11.y
    mad r10.y, r10.w, r10.y, r12.x
    add r10.y, r12.y, r10.y
    add r10.y, r11.x, r10.y
    mad r10.y, r10.y, l(0.111111112), l(-1.000000)
    mad r10.y, cb2[r10.z + 0].y, r10.y, l(1.000000)
    lt r10.z, r10.y, l(1.000000)
    if_nz r10.z
      lt r10.z, l(0.000000), r10.y
      if_nz r10.z
        mad r10.y, r10.y, l(15.000000), l(0.500000)
        ftou r10.y, r10.y
        umin r10.y, r10.y, l(15)
        ishl r10.z, r10.x, l(2)
        ishl r10.y, r10.y, r10.z
        or r7.w, r7.w, r10.y
        bfi r6.y, l(1), r9.w, l(1), r6.y
        iadd r10.x, r10.x, l(1)
      endif
      bfi r1.w, l(1), r9.w, l(1), r1.w
    endif
    iadd r9.w, r9.w, l(1)
  endif
  iadd r9.z, r9.z, l(1)
endloop
mul r0.y, r3.w, r5.w
min r0.z, r3.w, r5.w
mad r2.x, r5.w, r3.w, l(1.000000)
add r2.x, -r0.z, r2.x
mul r2.x, r2.x, r2.x
mad r0.z, -r5.w, r3.w, r0.z
mad r0.y, r2.x, r0.z, r0.y
mul r0.z, r4.x, r0.y
min r2.x, r4.x, r0.y
mad r3.w, r0.y, r4.x, l(1.000000)
add r3.w, -r2.x, r3.w
mul r3.w, r3.w, r3.w
mad r0.y, -r0.y, r4.x, r2.x
mad r0.y, r3.w, r0.y, r0.z
dp3 r0.z, r3.xyzx, r8.xyzx
mov_sat r2.x, r0.z
mad r9.xyz, r6.xzwx, l(2.040400, 2.040400, 2.040400, 0.000000), l(-0.332400, -0.332400, -0.332400, 0.000000)
mad r10.xyz, r6.xzwx, l(-4.795100, -4.795100, -4.795100, 0.000000), l(0.641700, 0.641700, 0.641700, 0.000000)
mad r6.xzw, r6.xxzw, l(2.755200, 0.000000, 2.755200, 2.755200), l(0.690300, 0.000000, 0.690300, 0.690300)
max r11.x, r4.z, l(0.040000)
mul r3.w, r11.x, r11.x
mad r4.x, -r11.x, r11.x, l(1.000000)
max r12.x, |r0.z|, l(0.000010)
min r4.z, r12.x, l(1.000000)
mul r5.w, r0.z, r0.z
mad r9.w, r5.w, l(2.000000), l(-1.000000)
mul r10.w, r3.w, r3.w
mad r11.z, r3.w, r3.w, l(-1.000000)
mul r11.w, r10.w, l(0.318309873)
add r12.w, r4.z, r4.z
dp3 r13.x, r5.xyzx, l(0.333333343, 0.333333343, 0.333333343, 0.000000)
mul_sat r13.y, r13.x, l(50.000000)
add r14.xyz, -r5.xyzx, r13.yyyy
mad r15.xyzw, r11.xxxx, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r13.z, r15.x, r15.x
mul r13.w, r11.x, l(0.577000)
max r11.y, r13.w, l(0.040000)
dp2 r13.w, l(0.850000, 0.150000, 0.000000, 0.000000), r11.xyxx
mul r14.w, r13.w, r13.w
mad r16.x, -r13.w, r13.w, l(1.000000)
mul r16.yzw, r11.yyxy, r11.yyxy
mad r11.x, -r11.y, r11.y, l(1.000000)
mul r17.xyz, r16.yzwy, r16.yzwy
mad r16.zw, r16.zzzw, r16.zzzw, l(0.000000, 0.000000, -1.000000, -1.000000)
mul r17.yz, r17.yyzy, l(0.000000, 0.318309873, 0.318309873, 0.000000)
add r11.y, -r13.x, r13.y
mad r18.xyzw, r13.wwww, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r13.w, r18.x, r18.x
mov r12.yz, l(0,1.000000,1.000000,0)
mov r17.w, l(0)
mov r19.xyzw, l(0,0,0,0)
mov r20.xyzw, l(0,0,0,0)
loop
  uge r21.x, r17.w, r0.w
  breakc_nz r21.x
  and r21.x, r17.w, l(-4)
  iadd r21.x, r21.x, l(16)
  ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r21.x, r0.x, r21.x, t11.xxxx
  bfi r21.y, l(2), l(3), r17.w, l(0)
  ushr r21.x, r21.x, r21.y
  and r21.x, r21.x, l(255)
  ge r21.y, cb2[r21.x + 0].x, l(0.000000)
  ult r21.z, r20.w, l(8)
  and r21.y, r21.z, r21.y
  if_nz r21.y
    ushr r21.y, r1.w, r19.w
    and r21.y, r21.y, l(1)
    ushr r21.w, r6.y, r19.w
    and r21.w, r21.w, l(1)
    ine r21.zw, r21.yyyw, l(0, 0, 0, 0)
    and r21.z, r21.w, r21.z
    if_nz r21.z
      ishl r21.z, r20.w, l(2)
      ushr r21.z, r7.w, r21.z
      and r21.z, r21.z, l(15)
      utof r21.z, r21.z
      mul r21.z, r21.z, l(0.0666666701)
      iadd r20.w, r20.w, l(1)
    else
      movc r21.z, r21.y, l(0), l(1.000000)
    endif
    iadd r19.w, r19.w, l(1)
  else
    mov r21.z, l(1.000000)
  endif
  ne r21.y, l(0.000000), cb3[r21.x + 256].w
  add r22.xyz, -r2.yzwy, cb4[r21.x + 0].xyzx
  dp3 r21.w, r22.xyzx, r22.xyzx
  rsq r22.w, r21.w
  mul r22.xyz, r22.wwww, r22.xyzx
  ne r22.w, l(0.000000), cb4[r21.x + 512].w
  if_nz r22.w
    mov r22.w, l(1.000000)
  else
    mul r23.x, cb4[r21.x + 0].w, cb4[r21.x + 0].w
    mul r23.x, r21.w, r23.x
    mad r23.x, -r23.x, r23.x, l(1.000000)
    max r23.x, r23.x, l(0.000000)
    mul r23.x, r23.x, r23.x
    add r23.y, r21.w, l(1.000000)
    mad r23.y, cb3[r21.x + 512].z, cb3[r21.x + 512].z, r23.y
    rcp r23.y, r23.y
    mul r22.w, r23.y, r23.x
  endif
  dp3 r23.x, r22.xyzx, cb3[r21.x + 0].xyzx
  add r23.x, r23.x, -cb3[r21.x + 512].x
  mul_sat r23.x, r23.x, cb3[r21.x + 512].y
  mul r23.x, r23.x, r23.x
  mul r23.x, r22.w, r23.x
  movc r21.y, r21.y, r23.x, r22.w
  lt r22.w, l(0.000000), r21.y
  if_nz r22.w
    and r22.w, l(3), cb3[r21.x + 768].x
    if_nz r22.w
      min r21.z, r0.y, r21.z
    else
      mov r21.z, r0.y
    endif
    lt r22.w, l(0.000000), r21.z
    if_nz r22.w
      dp3 r22.w, r22.xyzx, -cb3[r21.x + 0].xyzx
      lt r23.x, r22.w, l(0.000000)
      min r22.w, |r22.w|, l(1.000000)
      mad r23.y, r22.w, l(-0.0187292993), l(0.074261)
      mad r23.y, r23.y, r22.w, l(-0.212114394)
      mad r23.y, r23.y, r22.w, l(1.57072878)
      add r22.w, -r22.w, l(1.000000)
      sqrt r22.w, r22.w
      mul r22.w, r22.w, r23.y
      movc r23.y, r23.x, l(-1.000000), l(1.000000)
      and r23.x, r23.x, l(0x40490fdb)
      mad r22.w, r22.w, r23.y, r23.x
      mad r23.x, -r22.w, l(0.318309873), l(1.000000)
      utof r22.w, cb3[r21.x + 768].z
      add r22.w, r22.w, l(0.500000)
      mul r23.y, r22.w, cb0[0].w
      sample_l_indexable(texture2d)(float,float,float,float) r22.w, r23.xyxx, t7.yzwx, s2, l(0.000000)
      mul r23.xyz, r22.wwww, cb4[r21.x + 512].xyzx
      mad r24.xyz, r9.xyzx, r21.zzzz, r10.xyzx
      mad r24.xyz, r24.xyzx, r21.zzzz, r6.xzwx
      max r24.xyz, r24.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
      mul r24.xyz, r21.zzzz, r24.xyzx
      add r22.w, r2.x, r21.z
      lt r23.w, r22.w, l(0.000001)
      log r22.w, r22.w
      mul r22.w, r4.w, r22.w
      exp r22.w, r22.w
      movc r22.w, r23.w, l(0), r22.w
      add r21.z, r21.z, r22.w
      add_sat r21.z, r21.z, l(-1.000000)
      sqrt r21.w, r21.w
      max r21.w, r21.w, l(0.001000)
      div r21.x, cb3[r21.x + 512].z, r21.w
      if_nz r4.y
        mul_sat r21.w, r4.x, r21.x
        dp3 r22.w, r3.xyzx, r22.xyzx
        dp3 r23.w, r8.xyzx, r22.xyzx
        lt r24.w, l(0.000000), r21.w
        if_nz r24.w
          mad r25.x, -r21.w, r21.w, l(1.000000)
          sqrt r25.x, r25.x
          dp2 r25.y, r0.zzzz, r22.wwww
          add r25.z, -r23.w, r25.y
          lt r25.w, r25.z, r25.x
          not r26.x, r25.w
          if_nz r25.w
            mad r25.w, -r25.z, r25.z, l(1.000000)
            max r25.w, r25.w, l(0.000010)
            rsq r25.w, r25.w
            mul r25.w, r21.w, r25.w
            mad r26.y, -r25.z, r22.w, r0.z
            mul r26.z, r25.w, r26.y
            mad r25.z, -r25.z, r23.w, r9.w
            mad r26.w, -r22.w, r22.w, -r5.w
            add r26.w, r26.w, l(1.000000)
            mad r26.w, -r23.w, r23.w, r26.w
            mad_sat r25.y, r25.y, r23.w, r26.w
            sqrt r25.y, r25.y
            mul r25.yz, r25.yyzy, r25.wwww
            mul r26.w, r0.z, r25.y
            add r27.x, r26.w, r26.w
            mad r27.y, r22.w, r25.x, r0.z
            mad r25.w, r25.w, r26.y, r27.y
            mad r26.y, r23.w, r25.x, r25.z
            add r26.y, r26.y, l(1.000000)
            mul r27.zw, r25.yyyw, r26.yyyy
            mul r28.x, r25.w, r27.x
            mul r26.w, r26.w, r25.w
            mul r26.w, r26.w, l(0.500000)
            mad r26.w, r27.z, l(-0.500000), r26.w
            mad r28.y, -r27.z, l(2.000000), r28.x
            mul r28.x, r28.y, r28.x
            mad r27.z, r27.z, r27.z, r28.x
            mul r28.x, r26.y, r26.y
            mad r26.y, r23.w, r25.x, r26.y
            mad r26.y, r26.y, l(-0.500000), l(-0.500000)
            mul r26.yw, r26.yyyw, r27.wwww
            mad r26.y, r27.y, r28.x, r26.y
            mad r25.w, r25.w, r26.y, r27.z
            mul r26.y, r26.w, r26.w
            mad r27.y, r25.w, r25.w, -r26.y
            mad r27.y, r27.y, l(0.500000), r26.y
            max r27.y, r27.y, l(0.000010)
            rcp r27.y, r27.y
            mul r25.w, r25.w, r26.w
            mul r25.w, r27.y, r25.w
            min r25.w, r25.w, l(1.000000)
            max r25.w, r25.w, l(-1.000000)
            mad r26.y, -r26.y, r27.y, l(1.000000)
            max r26.y, r26.y, l(-1.000000)
            mul r25.y, r25.y, r25.w
            mad r25.y, r26.y, r26.z, r25.y
            mul r25.w, r27.x, r25.w
            mad r25.z, r26.y, r25.z, r25.w
            mad r25.y, r22.w, r25.x, r25.y
            mad r23.w, r23.w, r25.x, r25.z
          else
            mov r25.y, r22.w
          endif
        else
          mov r25.y, r22.w
          mov r26.x, l(0)
        endif
        mad r25.x, r23.w, l(2.000000), l(2.000000)
        max r25.x, r25.x, l(0.000010)
        rsq r25.x, r25.x
        add r25.y, r0.z, r25.y
        mul_sat r27.x, r25.x, r25.y
        mad_sat r27.y, r25.x, r23.w, r25.x
        movc r25.xy, r26.xxxx, r12.yxyy, r27.xyxx
        mov_sat r21.x, r21.x
        max r23.w, r22.w, l(0.000000)
        lt r23.w, r23.w, r21.x
        max r25.z, -r21.x, r22.w
        add r25.z, r21.x, r25.z
        mul r25.z, r25.z, r25.z
        mul r25.w, r21.x, l(4.000000)
        rcp r25.w, r25.w
        mul r25.z, r25.w, r25.z
        movc_sat r22.w, r23.w, r25.z, r22.w
        mul r23.w, r25.x, r25.x
        mad r23.w, r23.w, r11.z, l(1.000000)
        mul r23.w, r23.w, r23.w
        rcp r23.w, r23.w
        mul r23.w, r11.w, r23.w
        mul r25.x, r12.w, r22.w
        add r25.z, r4.z, r22.w
        mad r25.z, -r12.w, r22.w, r25.z
        mad r25.x, r3.w, r25.z, r25.x
        rcp r25.x, r25.x
        mul r25.x, r25.x, l(0.500000)
        add r25.z, -r25.y, l(1.000000)
        mul r25.w, r25.z, r25.z
        mul r25.w, r25.w, r25.w
        mul r25.z, r25.z, r25.w
        mad r26.xyz, r25.zzzz, r14.xyzx, r5.xyzx
        mul r25.z, r22.w, l(-9.280000)
        exp r25.z, r25.z
        min r25.z, r13.z, r25.z
        mad r25.z, r25.z, r15.x, r15.y
        mad r25.zw, r25.zzzz, l(0.000000, 0.000000, -1.040000, 1.040000), r15.zzzw
        mul r25.w, r13.y, r25.w
        mad_sat r25.z, r13.x, r25.z, r25.w
        add r25.z, -r25.z, l(1.000000)
        mul r25.z, r22.w, r25.z
        max r25.y, r25.y, l(0.000010)
        rcp r25.y, r25.y
        mul r25.w, r21.w, l(0.250000)
        mad r21.w, r3.w, l(3.000000), r21.w
        mul r21.w, r21.w, r25.w
        mad r21.w, r21.w, r25.y, r10.w
        rcp r21.w, r21.w
        mul r21.w, r10.w, r21.w
        movc r21.w, r24.w, r21.w, l(1.000000)
        mul r22.w, r22.w, r23.w
        mul r22.w, r25.x, r22.w
        mul r25.xyw, r26.xyxz, r22.wwww
        mul r25.xyw, r21.wwww, r25.xyxw
        mul r21.w, r25.z, l(0.318309873)
        mul r26.xyz, r7.xyzx, r21.wwww
      else
        if_nz r8.w
          mul_sat r21.w, r16.x, r21.x
          dp3 r22.w, r3.xyzx, r22.xyzx
          dp3 r22.x, r8.xyzx, r22.xyzx
          lt r22.y, l(0.000000), r21.w
          if_nz r22.y
            mad r22.y, -r21.w, r21.w, l(1.000000)
            sqrt r22.y, r22.y
            dp2 r22.z, r0.zzzz, r22.wwww
            add r23.w, -r22.x, r22.z
            lt r24.w, r23.w, r22.y
            not r25.z, r24.w
            if_nz r24.w
              mad r24.w, -r23.w, r23.w, l(1.000000)
              max r24.w, r24.w, l(0.000010)
              rsq r24.w, r24.w
              mul r21.w, r21.w, r24.w
              mad r24.w, -r23.w, r22.w, r0.z
              mul r26.w, r21.w, r24.w
              mad r23.w, -r23.w, r22.x, r9.w
              mul r23.w, r21.w, r23.w
              mad r27.x, -r22.w, r22.w, -r5.w
              add r27.x, r27.x, l(1.000000)
              mad r27.x, -r22.x, r22.x, r27.x
              mad_sat r22.z, r22.z, r22.x, r27.x
              sqrt r22.z, r22.z
              mul r22.z, r21.w, r22.z
              mul r27.x, r0.z, r22.z
              add r27.y, r27.x, r27.x
              mad r27.z, r22.w, r22.y, r0.z
              mad r21.w, r21.w, r24.w, r27.z
              mad r24.w, r22.x, r22.y, r23.w
              add r24.w, r24.w, l(1.000000)
              mul r27.w, r22.z, r24.w
              mul r28.x, r21.w, r24.w
              mul r28.y, r21.w, r27.y
              mul r27.x, r27.x, r21.w
              mul r27.x, r27.x, l(0.500000)
              mad r27.x, r27.w, l(-0.500000), r27.x
              mul r27.x, r27.x, r28.x
              mad r28.z, -r27.w, l(2.000000), r28.y
              mul r28.y, r28.z, r28.y
              mad r27.w, r27.w, r27.w, r28.y
              mul r28.y, r24.w, r24.w
              mad r24.w, r22.x, r22.y, r24.w
              mad r24.w, r24.w, l(-0.500000), l(-0.500000)
              mul r24.w, r24.w, r28.x
              mad r24.w, r27.z, r28.y, r24.w
              mad r21.w, r21.w, r24.w, r27.w
              mul r24.w, r27.x, r27.x
              mad r27.z, r21.w, r21.w, -r24.w
              mad r27.z, r27.z, l(0.500000), r24.w
              max r27.z, r27.z, l(0.000010)
              rcp r27.z, r27.z
              mul r21.w, r21.w, r27.x
              mul r21.w, r27.z, r21.w
              min r21.w, r21.w, l(1.000000)
              max r21.w, r21.w, l(-1.000000)
              mad r24.w, -r24.w, r27.z, l(1.000000)
              max r24.w, r24.w, l(-1.000000)
              mul r22.z, r22.z, r21.w
              mad r22.z, r24.w, r26.w, r22.z
              mul r21.w, r27.y, r21.w
              mad r21.w, r24.w, r23.w, r21.w
              mad r22.z, r22.w, r22.y, r22.z
              mad r22.x, r22.x, r22.y, r21.w
            else
              mov r22.xz, r22.xxwx
            endif
          else
            mov r22.xz, r22.xxwx
            mov r25.z, l(0)
          endif
          mad r21.w, r22.x, l(2.000000), l(2.000000)
          max r21.w, r21.w, l(0.000010)
          rsq r21.w, r21.w
          add r22.y, r0.z, r22.z
          mul_sat r27.x, r21.w, r22.y
          mad_sat r27.y, r21.w, r22.x, r21.w
          movc r22.xy, r25.zzzz, r12.zxzz, r27.xyxx
          mov_sat r21.w, r21.x
          max r22.z, r22.w, l(0.000000)
          lt r22.z, r22.z, r21.w
          max r23.w, -r21.w, r22.w
          add r23.w, r21.w, r23.w
          mul r23.w, r23.w, r23.w
          mul r21.w, r21.w, l(4.000000)
          rcp r21.w, r21.w
          mul r21.w, r21.w, r23.w
          movc_sat r21.w, r22.z, r21.w, r22.w
          mul_sat r22.z, r4.x, r21.x
          max r22.w, r22.y, l(0.000010)
          rcp r22.w, r22.w
          lt r23.w, l(0.000000), r22.z
          mul r24.w, r22.z, l(0.250000)
          mad r22.z, r3.w, l(3.000000), r22.z
          mul r22.z, r22.z, r24.w
          mad r22.z, r22.z, r22.w, r10.w
          rcp r22.z, r22.z
          mul r22.z, r10.w, r22.z
          movc r27.x, r23.w, r22.z, l(1.000000)
          mul_sat r21.x, r11.x, r21.x
          lt r22.z, l(0.000000), r21.x
          mul r23.w, r21.x, l(0.250000)
          mad r21.x, r16.y, l(3.000000), r21.x
          mul r21.x, r21.x, r23.w
          mad r21.x, r21.x, r22.w, r17.x
          rcp r21.x, r21.x
          mul r21.x, r17.x, r21.x
          movc r27.y, r22.z, r21.x, l(1.000000)
          mul r21.x, r22.x, r22.x
          mad r22.xz, r21.xxxx, r16.zzwz, l(1.000000, 0.000000, 1.000000, 0.000000)
          mul r22.xz, r22.xxzx, r22.xxzx
          rcp r22.xz, r22.xxzx
          mul r22.xz, r17.yyzy, r22.xxzx
          mul r21.x, r12.w, r21.w
          add r22.w, r4.z, r21.w
          mad r22.w, -r12.w, r21.w, r22.w
          mad r21.x, r14.w, r22.w, r21.x
          rcp r21.x, r21.x
          mul r21.x, r21.x, r21.w
          add r22.y, -r22.y, l(1.000000)
          mul r22.w, r22.y, r22.y
          mul r22.w, r22.w, r22.w
          mul r22.y, r22.y, r22.w
          mad r22.y, r22.y, r11.y, r13.x
          mul r22.w, r21.w, l(-9.280000)
          exp r22.w, r22.w
          min r22.w, r13.w, r22.w
          mad r22.w, r22.w, r18.x, r18.y
          mad r27.zw, r22.wwww, l(0.000000, 0.000000, -1.040000, 1.040000), r18.zzzw
          mad_sat r22.w, r27.z, l(0.032500), r27.w
          add r22.w, -r22.w, l(1.000000)
          mul r21.w, r21.w, r22.w
          mul r21.x, r21.x, r22.y
          mul r21.x, r21.x, l(0.500000)
          mul r22.xy, r22.xzxx, r27.xyxx
          dp2 r22.x, l(0.850000, 0.150000, 0.000000, 0.000000), r22.xyxx
          mul r25.xyw, r21.xxxx, r22.xxxx
          mul r21.x, r21.w, l(0.318309873)
          mul r26.xyz, r7.xyzx, r21.xxxx
        else
          mov r26.xyz, l(0,0,0,0)
          mov r25.xyw, l(0,0,0,0)
        endif
      endif
      mul r22.xyz, r23.xyzx, r25.xywx
      mul r22.xyz, r21.yyyy, r22.xyzx
      mul r21.xzw, r21.zzzz, r22.xxyz
      mul r22.xyz, r23.xyzx, r26.xyzx
      mul r22.xyz, r21.yyyy, r22.xyzx
      mul r22.xyz, r24.xyzx, r22.xyzx
    else
      mov r22.xyz, l(0,0,0,0)
      mov r21.xzw, l(0,0,0,0)
    endif
  else
    mov r22.xyz, l(0,0,0,0)
    mov r21.xzw, l(0,0,0,0)
  endif
  add r19.xyz, r19.xyzx, r22.xyzx
  add r20.xyz, r20.xyzx, r21.xzwx
  iadd r17.w, r17.w, l(1)
endloop
ult r0.xy, r1.xyxx, cb0[1].zwzz
and r0.x, r0.y, r0.x
if_nz r0.x
  ld_indexable(texture2d)(float,float,float,float) r0.xyzw, r1.xyzz, t8.xyzw
  add r2.xyz, r19.xyzx, r20.xyzx
  dp3 r2.w, r19.xyzx, l(0.212600, 0.715200, 0.072200, 0.000000)
  mad r0.xyzw, r0.xyzw, cb1[128].yyyy, r2.xyzw
  mul r0.xyzw, r0.xyzw, cb1[128].xxxx
  store_uav_typed u0.xyzw, r1.xyyy, r0.xyzw
endif
ret
// Approximately 0 instruction slots used
