//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.9 on Mon Aug 31 08:54:04 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[5], immediateIndexed
dcl_constantbuffer CB1[140], immediateIndexed
dcl_constantbuffer CB2[1280], dynamicIndexed
dcl_constantbuffer CB3[1024], dynamicIndexed
dcl_constantbuffer CB4[768], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2darray (float,float,float,float) t9
dcl_resource_buffer (uint,uint,uint,uint) t10
dcl_resource_structured t11, 80
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.xy
dcl_temps 24
dcl_thread_group 16, 16, 1
iadd r0.x, vThreadGroupID.x, l(0x00008700)
ld_indexable(buffer)(uint,uint,uint,uint) r0.x, r0.xxxx, t10.xyzw
and r1.x, r0.x, l(255)
ushr r1.y, r0.x, l(8)
imad r0.yz, r1.xxyx, l(0, 16, 16, 0), vThreadIDInGroup.xxyx
iadd r1.xy, r0.yzyy, cb0[1].xyxx
ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r0.w, r0.x, l(0), t11.xxxx
ine r2.x, cb0[4].y, l(0)
ult r2.y, l(64), r0.w
and r2.x, r2.y, r2.x
if_nz r2.x
  store_uav_typed u0.xyzw, r1.xyyy, l(2.000000,0,0,1.000000)
  ret
endif
utof r0.yz, r0.yyzy
add r0.yz, r0.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
iadd r2.xy, -cb0[1].xyxx, cb0[1].zwzz
utof r2.xy, r2.xyxx
div r0.yz, r0.yyzy, r2.xxyx
mad r0.yz, r0.yyzy, l(0.000000, 2.000000, -2.000000, 0.000000), l(0.000000, -1.000000, 1.000000, 0.000000)
mov r1.z, l(0)
ld_indexable(texture2d)(float,float,float,float) r2.x, r1.xyzz, t4.xyzw
mad r2.y, r2.x, cb1[57].x, cb1[57].y
mad r2.x, r2.x, cb1[57].z, -cb1[57].w
rcp r2.x, r2.x
add r2.x, r2.x, r2.y
mul r0.yz, r0.yyzy, r2.xxxx
mul r3.xyzw, r0.zzzz, cb1[41].xyzw
mad r3.xyzw, r0.yyyy, cb1[40].xyzw, r3.xyzw
mad r3.xyzw, r2.xxxx, cb1[42].xyzw, r3.xyzw
add r3.xyzw, r3.xyzw, cb1[43].xyzw
div r2.yzw, r3.xxyz, r3.wwww
umin r0.w, r0.w, l(64)
ld_indexable(texture2d)(float,float,float,float) r3.xyz, r1.xyzz, t1.xyzw
ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.xyzz, t2.xyzw
ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r1.xyzz, t3.xyzw
mad r3.xyz, r3.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
dp3 r3.w, r3.xyzx, r3.xyzx
rsq r3.w, r3.w
mul r3.xyz, r3.wwww, r3.xyzx
mad r3.w, r4.w, l(255.000000), l(0.500000)
ftou r3.w, r3.w
and r6.xy, r3.wwww, l(15, 16, 0, 0)
add r3.w, -r4.x, l(1.000000)
mul r7.xyz, r5.xyzx, r3.wwww
mul r4.yw, r4.yyyz, r4.yyyz
mul r6.z, r4.y, l(0.160000)
mad r5.xyz, -r4.yyyy, l(0.160000, 0.160000, 0.160000, 0.000000), r5.xyzx
mad r5.xyz, r4.xxxx, r5.xyzx, r6.zzzz
mad r7.xyz, r7.xyzx, cb1[132].wwww, cb1[132].xyzx
ieq r6.xzw, r6.xxxx, l(1, 0, 2, 5)
or r4.xy, r6.zwzz, r6.xxxx
mad r6.xzw, r5.xxyz, cb1[133].wwww, cb1[133].xxyz
movc r5.xyz, r4.xxxx, r6.xzwx, r5.xyzx
mad r6.xzw, r5.xxyz, l(0.450000, 0.000000, 0.450000, 0.450000), r7.xxyz
movc r7.xyz, r6.yyyy, r3.wwww, r7.xyzx
utof r8.xy, r1.xyxx
add r8.xy, r8.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mul r8.xy, r8.xyxx, cb1[126].zwzz
sample_l_indexable(texture2d)(float,float,float,float) r3.w, r8.xyxx, t5.yzwx, s0, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r4.x, r8.xyxx, t6.yxzw, s1, l(0.000000)
add r8.xyz, -r2.yzwy, cb1[59].xyzx
dp3 r6.y, r8.xyzx, r8.xyzx
rsq r6.y, r6.y
mul r8.xyz, r6.yyyy, r8.xyzx
ishl r1.w, cb1[139].z, l(3)
and r9.xyz, r1.xywx, l(63, 63, 63, 0)
mov r9.w, l(0)
ld_indexable(texture3d)(float,float,float,float) r9.xy, r9.xyzw, t0.xyzw
mad r9.xy, r9.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
lt r9.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r9.xxxy
lt r10.xy, r9.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
iadd r9.zw, -r9.zzzw, r10.xxxy
itof r9.zw, r9.zzzw
add r9.xy, -|r9.xyxx|, l(1.000000, 1.000000, 0.000000, 0.000000)
sqrt r9.xy, r9.xyxx
add r9.xy, -r9.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r9.xy, r9.xyxx, r9.zwzz
mul r9.xy, r9.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000)
mov r1.w, l(0)
mov r6.y, l(0)
mov r7.w, l(0)
mov r8.w, l(0)
mov r9.zw, l(0,0,0,0)
loop
  ult r10.x, r8.w, r0.w
  ult r10.y, r9.w, l(8)
  and r10.x, r10.y, r10.x
  breakc_z r10.x
  and r10.x, r8.w, l(-4)
  iadd r10.x, r10.x, l(16)
  ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r10.x, r0.x, r10.x, t11.xxxx
  bfi r10.y, l(2), l(3), r8.w, l(0)
  ushr r10.x, r10.x, r10.y
  and r10.y, r10.x, l(255)
  ge r10.z, cb2[r10.y + 0].x, l(0.000000)
  if_nz r10.z
    bfi r10.x, l(8), l(2), r10.x, l(0)
    mul r11.xyzw, r0.zzzz, cb2[r10.x + 257].xyzw
    mad r11.xyzw, r0.yyyy, cb2[r10.x + 256].xyzw, r11.xyzw
    mad r11.xyzw, r2.xxxx, cb2[r10.x + 258].xyzw, r11.xyzw
    add r11.xyzw, r11.xyzw, cb2[r10.x + 259].xyzw
    rcp r10.x, r11.w
    mul r10.xz, r10.xxxx, r11.xxyx
    add r10.w, l(1.000000), -cb2[r10.y + 0].w
    max r10.w, r10.w, l(0.000000)
    mul r11.xy, r9.xyxx, r10.wwww
    mad r10.xz, r10.xxzx, cb0[3].xxyx, r11.xxyx
    add r10.xz, r10.xxzx, l(-0.500000, 0.000000, -0.500000, 0.000000)
    round_z r11.xy, r10.xzxx
    add r10.xz, r10.xxzx, -r11.xxyx
    add r11.xy, r11.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
    mul r12.xy, r11.xyxx, cb0[3].zwzz
    mov r12.z, cb2[r10.y + 0].x
    gather4_aoffimmi_indexable(-1,-1,0)(texture2darray)(float,float,float,float) r13.xyzw, r12.xyzx, t9.xyzw, s3.x
    add r14.xyzw, -r11.zzzz, r13.xyzw
    mad_sat r14.xyzw, r14.xyzw, cb2[r10.y + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r13.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r13.xyzw
    and r13.xyzw, r13.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r13.xyzw, r13.xyzw, r14.xyzw
    min r13.xyzw, r13.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(1,-1,0)(texture2darray)(float,float,float,float) r14.xyzw, r12.xyzx, t9.xyzw, s3.x
    add r15.xyzw, -r11.zzzz, r14.xyzw
    mad_sat r15.xyzw, r15.xyzw, cb2[r10.y + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r14.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r14.xyzw
    and r14.xyzw, r14.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r14.xyzw, r14.xyzw, r15.xyzw
    min r14.xyzw, r14.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(-1,1,0)(texture2darray)(float,float,float,float) r15.xyzw, r12.xyzx, t9.xyzw, s3.x
    add r16.xyzw, -r11.zzzz, r15.xyzw
    mad_sat r16.xyzw, r16.xyzw, cb2[r10.y + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r15.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r15.xyzw
    and r15.xyzw, r15.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r15.xyzw, r15.xyzw, r16.xyzw
    min r15.xyzw, r15.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(1,1,0)(texture2darray)(float,float,float,float) r12.xyzw, r12.xyzx, t9.xyzw, s3.x
    add r11.xyzw, -r11.zzzz, r12.xyzw
    mad_sat r11.xyzw, r11.xyzw, cb2[r10.y + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r12.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r12.xyzw
    and r12.xyzw, r12.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r11.xyzw, r11.xyzw, r12.xyzw
    min r11.xyzw, r11.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    add r12.xy, -r13.wxww, r14.zyzz
    mad r12.xy, r10.xxxx, r12.xyxx, r13.wxww
    add r12.xy, r13.zyzz, r12.xyxx
    add r12.xy, r14.wxww, r12.xyxx
    add r11.yz, -r15.wwxw, r11.zzyz
    mad r10.xw, r10.xxxx, r11.yyyz, r15.wwwx
    add r10.xw, r15.zzzy, r10.xxxw
    add r10.xw, r11.wwwx, r10.xxxw
    add r10.w, -r12.x, r10.w
    mad r10.z, r10.z, r10.w, r12.x
    add r10.z, r12.y, r10.z
    add r10.x, r10.x, r10.z
    mad r10.x, r10.x, l(0.111111112), l(-1.000000)
    mad r10.x, cb2[r10.y + 0].y, r10.x, l(1.000000)
    lt r10.y, r10.x, l(1.000000)
    if_nz r10.y
      lt r10.y, l(0.000000), r10.x
      if_nz r10.y
        mad r10.x, r10.x, l(15.000000), l(0.500000)
        ftou r10.x, r10.x
        umin r10.x, r10.x, l(15)
        ishl r10.y, r9.w, l(2)
        ishl r10.x, r10.x, r10.y
        or r7.w, r7.w, r10.x
        bfi r6.y, l(1), r9.z, l(1), r6.y
        iadd r9.w, r9.w, l(1)
      endif
      bfi r1.w, l(1), r9.z, l(1), r1.w
    endif
    iadd r9.z, r9.z, l(1)
  endif
  iadd r8.w, r8.w, l(1)
endloop
mul r0.y, r3.w, r5.w
min r0.z, r3.w, r5.w
mad r2.x, r5.w, r3.w, l(1.000000)
add r2.x, -r0.z, r2.x
mul r2.x, r2.x, r2.x
mad r0.z, -r5.w, r3.w, r0.z
mad r0.y, r2.x, r0.z, r0.y
mul r0.z, r4.x, r0.y
min r2.x, r4.x, r0.y
mad r3.w, r0.y, r4.x, l(1.000000)
add r3.w, -r2.x, r3.w
mul r3.w, r3.w, r3.w
mad r0.y, -r0.y, r4.x, r2.x
mad r0.y, r3.w, r0.y, r0.z
dp3 r0.z, r3.xyzx, r8.xyzx
mov_sat r2.x, r0.z
mad r9.xyz, r6.xzwx, l(2.040400, 2.040400, 2.040400, 0.000000), l(-0.332400, -0.332400, -0.332400, 0.000000)
mad r10.xyz, r6.xzwx, l(-4.795100, -4.795100, -4.795100, 0.000000), l(0.641700, 0.641700, 0.641700, 0.000000)
mad r6.xzw, r6.xxzw, l(2.755200, 0.000000, 2.755200, 2.755200), l(0.690300, 0.000000, 0.690300, 0.690300)
max r3.w, r4.z, l(0.040000)
mul r4.x, r3.w, r3.w
mad r4.z, -r3.w, r3.w, l(1.000000)
max r11.y, |r0.z|, l(0.000010)
min r5.w, r11.y, l(1.000000)
mul r8.w, r0.z, r0.z
mad r9.w, r8.w, l(2.000000), l(-1.000000)
mul r10.w, r4.x, r4.x
mad r11.z, r4.x, r4.x, l(-1.000000)
mul r11.w, r10.w, l(0.318309873)
add r12.x, r5.w, r5.w
dp3 r12.y, r5.xyzx, l(0.333333343, 0.333333343, 0.333333343, 0.000000)
mul_sat r12.z, r12.y, l(50.000000)
add r13.xyz, -r5.xyzx, r12.zzzz
mad r14.xyzw, r3.wwww, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r3.w, r14.x, r14.x
mov r11.x, l(1.000000)
mov r16.xyz, l(0,0,0,0)
mov r12.w, l(0)
mov r13.w, l(0)
mov r15.xyzw, l(0,0,0,0)
loop
  uge r16.w, r12.w, r0.w
  breakc_nz r16.w
  and r16.w, r12.w, l(-4)
  iadd r16.w, r16.w, l(16)
  ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r16.w, r0.x, r16.w, t11.xxxx
  bfi r17.x, l(2), l(3), r12.w, l(0)
  ushr r16.w, r16.w, r17.x
  and r16.w, r16.w, l(255)
  ge r17.x, cb2[r16.w + 0].x, l(0.000000)
  ult r17.y, r15.w, l(8)
  and r17.x, r17.y, r17.x
  if_nz r17.x
    ushr r17.x, r1.w, r13.w
    and r17.x, r17.x, l(1)
    ushr r17.z, r6.y, r13.w
    and r17.z, r17.z, l(1)
    ine r17.yz, r17.xxzx, l(0, 0, 0, 0)
    and r17.y, r17.z, r17.y
    if_nz r17.y
      ishl r17.y, r15.w, l(2)
      ushr r17.y, r7.w, r17.y
      and r17.y, r17.y, l(15)
      utof r17.y, r17.y
      mul r17.y, r17.y, l(0.0666666701)
      iadd r15.w, r15.w, l(1)
    else
      movc r17.y, r17.x, l(0), l(1.000000)
    endif
    iadd r13.w, r13.w, l(1)
  else
    mov r17.y, l(1.000000)
  endif
  ne r17.x, l(0.000000), cb3[r16.w + 256].w
  add r18.xyz, -r2.yzwy, cb4[r16.w + 0].xyzx
  dp3 r17.z, r18.xyzx, r18.xyzx
  rsq r17.w, r17.z
  mul r18.xyz, r17.wwww, r18.xyzx
  ne r17.w, l(0.000000), cb4[r16.w + 512].w
  if_nz r17.w
    mov r17.w, l(1.000000)
  else
    mul r18.w, cb4[r16.w + 0].w, cb4[r16.w + 0].w
    mul r18.w, r17.z, r18.w
    mad r18.w, -r18.w, r18.w, l(1.000000)
    max r18.w, r18.w, l(0.000000)
    mul r18.w, r18.w, r18.w
    add r19.x, r17.z, l(1.000000)
    mad r19.x, cb3[r16.w + 512].z, cb3[r16.w + 512].z, r19.x
    rcp r19.x, r19.x
    mul r17.w, r18.w, r19.x
  endif
  dp3 r18.w, r18.xyzx, cb3[r16.w + 0].xyzx
  add r18.w, r18.w, -cb3[r16.w + 512].x
  mul_sat r18.w, r18.w, cb3[r16.w + 512].y
  mul r18.w, r18.w, r18.w
  mul r18.w, r17.w, r18.w
  movc r17.x, r17.x, r18.w, r17.w
  lt r17.w, l(0.000000), r17.x
  if_nz r17.w
    and r17.w, l(3), cb3[r16.w + 768].x
    if_nz r17.w
      min r17.y, r0.y, r17.y
    else
      mov r17.y, r0.y
    endif
    lt r17.w, l(0.000000), r17.y
    if_nz r17.w
      dp3 r17.w, r18.xyzx, -cb3[r16.w + 0].xyzx
      lt r18.w, r17.w, l(0.000000)
      min r17.w, |r17.w|, l(1.000000)
      mad r19.x, r17.w, l(-0.0187292993), l(0.074261)
      mad r19.x, r19.x, r17.w, l(-0.212114394)
      mad r19.x, r19.x, r17.w, l(1.57072878)
      add r17.w, -r17.w, l(1.000000)
      sqrt r17.w, r17.w
      mul r17.w, r17.w, r19.x
      movc r19.x, r18.w, l(-1.000000), l(1.000000)
      and r18.w, r18.w, l(0x40490fdb)
      mad r17.w, r17.w, r19.x, r18.w
      mad r19.x, -r17.w, l(0.318309873), l(1.000000)
      utof r17.w, cb3[r16.w + 768].z
      add r17.w, r17.w, l(0.500000)
      mul r19.y, r17.w, cb0[0].w
      sample_l_indexable(texture2d)(float,float,float,float) r17.w, r19.xyxx, t7.yzwx, s2, l(0.000000)
      mul r19.xyz, r17.wwww, cb4[r16.w + 512].xyzx
      mad r20.xyz, r9.xyzx, r17.yyyy, r10.xyzx
      mad r20.xyz, r20.xyzx, r17.yyyy, r6.xzwx
      max r20.xyz, r20.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
      mul r20.xyz, r17.yyyy, r20.xyzx
      add r17.w, r2.x, r17.y
      lt r18.w, r17.w, l(0.000001)
      log r17.w, r17.w
      mul r17.w, r4.w, r17.w
      exp r17.w, r17.w
      movc r17.w, r18.w, l(0), r17.w
      add r17.y, r17.y, r17.w
      add_sat r17.y, r17.y, l(-1.000000)
      sqrt r17.z, r17.z
      max r17.z, r17.z, l(0.001000)
      div r16.w, cb3[r16.w + 512].z, r17.z
      if_nz r4.y
        mul_sat r17.z, r4.z, r16.w
        dp3 r17.w, r3.xyzx, r18.xyzx
        dp3 r18.x, r8.xyzx, r18.xyzx
        lt r18.y, l(0.000000), r17.z
        if_nz r18.y
          mad r18.z, -r17.z, r17.z, l(1.000000)
          sqrt r18.z, r18.z
          dp2 r18.w, r0.zzzz, r17.wwww
          add r19.w, -r18.x, r18.w
          lt r20.w, r19.w, r18.z
          not r21.x, r20.w
          if_nz r20.w
            mad r20.w, -r19.w, r19.w, l(1.000000)
            max r20.w, r20.w, l(0.000010)
            rsq r20.w, r20.w
            mul r20.w, r17.z, r20.w
            mad r21.y, -r19.w, r17.w, r0.z
            mul r21.z, r20.w, r21.y
            mad r19.w, -r19.w, r18.x, r9.w
            mul r19.w, r19.w, r20.w
            mad r21.w, -r17.w, r17.w, -r8.w
            add r21.w, r21.w, l(1.000000)
            mad r21.w, -r18.x, r18.x, r21.w
            mad_sat r18.w, r18.w, r18.x, r21.w
            sqrt r18.w, r18.w
            mul r18.w, r18.w, r20.w
            mul r21.w, r0.z, r18.w
            add r22.x, r21.w, r21.w
            mad r22.y, r17.w, r18.z, r0.z
            mad r20.w, r20.w, r21.y, r22.y
            mad r21.y, r18.x, r18.z, r19.w
            add r21.y, r21.y, l(1.000000)
            mul r22.z, r18.w, r21.y
            mul r22.w, r20.w, r21.y
            mul r23.x, r20.w, r22.x
            mul r21.w, r21.w, r20.w
            mul r21.w, r21.w, l(0.500000)
            mad r21.w, r22.z, l(-0.500000), r21.w
            mad r23.y, -r22.z, l(2.000000), r23.x
            mul r23.x, r23.y, r23.x
            mad r22.z, r22.z, r22.z, r23.x
            mul r23.x, r21.y, r21.y
            mad r21.y, r18.x, r18.z, r21.y
            mad r21.y, r21.y, l(-0.500000), l(-0.500000)
            mul r21.yw, r21.yyyw, r22.wwww
            mad r21.y, r22.y, r23.x, r21.y
            mad r20.w, r20.w, r21.y, r22.z
            mul r21.y, r21.w, r21.w
            mad r22.y, r20.w, r20.w, -r21.y
            mad r22.y, r22.y, l(0.500000), r21.y
            max r22.y, r22.y, l(0.000010)
            rcp r22.y, r22.y
            mul r20.w, r20.w, r21.w
            mul r20.w, r22.y, r20.w
            min r20.w, r20.w, l(1.000000)
            max r20.w, r20.w, l(-1.000000)
            mad r21.y, -r21.y, r22.y, l(1.000000)
            max r21.y, r21.y, l(-1.000000)
            mul r18.w, r18.w, r20.w
            mad r18.w, r21.y, r21.z, r18.w
            mul r20.w, r22.x, r20.w
            mad r19.w, r21.y, r19.w, r20.w
            mad r18.w, r17.w, r18.z, r18.w
            mad r18.x, r18.x, r18.z, r19.w
          else
            mov r18.w, r17.w
          endif
        else
          mov r18.w, r17.w
          mov r21.x, l(0)
        endif
        mad r18.z, r18.x, l(2.000000), l(2.000000)
        max r18.z, r18.z, l(0.000010)
        rsq r18.z, r18.z
        add r18.w, r0.z, r18.w
        mul_sat r22.x, r18.z, r18.w
        mad_sat r22.y, r18.z, r18.x, r18.z
        movc r18.xz, r21.xxxx, r11.xxyx, r22.xxyx
        mov_sat r16.w, r16.w
        max r18.w, r17.w, l(0.000000)
        lt r18.w, r18.w, r16.w
        max r19.w, -r16.w, r17.w
        add r19.w, r16.w, r19.w
        mul r19.w, r19.w, r19.w
        mul r16.w, r16.w, l(4.000000)
        rcp r16.w, r16.w
        mul r16.w, r16.w, r19.w
        movc_sat r16.w, r18.w, r16.w, r17.w
        mul r17.w, r18.x, r18.x
        mad r17.w, r17.w, r11.z, l(1.000000)
        mul r17.w, r17.w, r17.w
        rcp r17.w, r17.w
        mul r17.w, r11.w, r17.w
        mul r18.x, r12.x, r16.w
        add r18.w, r5.w, r16.w
        mad r18.w, -r12.x, r16.w, r18.w
        mad r18.x, r4.x, r18.w, r18.x
        rcp r18.x, r18.x
        mul r18.x, r18.x, l(0.500000)
        add r18.w, -r18.z, l(1.000000)
        mul r19.w, r18.w, r18.w
        mul r19.w, r19.w, r19.w
        mul r18.w, r18.w, r19.w
        mad r21.xyz, r18.wwww, r13.xyzx, r5.xyzx
        mul r18.w, r16.w, l(-9.280000)
        exp r18.w, r18.w
        min r18.w, r3.w, r18.w
        mad r18.w, r18.w, r14.x, r14.y
        mad r22.xy, r18.wwww, l(-1.040000, 1.040000, 0.000000, 0.000000), r14.zwzz
        mul r18.w, r12.z, r22.y
        mad_sat r18.w, r12.y, r22.x, r18.w
        add r18.w, -r18.w, l(1.000000)
        mul r18.w, r16.w, r18.w
        max r18.z, r18.z, l(0.000010)
        rcp r18.z, r18.z
        mul r19.w, r17.z, l(0.250000)
        mad r17.z, r4.x, l(3.000000), r17.z
        mul r17.z, r17.z, r19.w
        mad r17.z, r17.z, r18.z, r10.w
        rcp r17.z, r17.z
        mul r17.z, r10.w, r17.z
        movc r17.z, r18.y, r17.z, l(1.000000)
        mul r16.w, r16.w, r17.w
        mul r16.w, r18.x, r16.w
        mul r18.xyz, r21.xyzx, r16.wwww
        mul r18.xyz, r17.zzzz, r18.xyzx
        mul r16.w, r18.w, l(0.318309873)
        mul r21.xyz, r7.xyzx, r16.wwww
      else
        mov r21.xyz, l(0,0,0,0)
        mov r18.xyz, l(0,0,0,0)
      endif
      mul r18.xyz, r19.xyzx, r18.xyzx
      mul r18.xyz, r17.xxxx, r18.xyzx
      mul r17.yzw, r17.yyyy, r18.xxyz
      mul r18.xyz, r19.xyzx, r21.xyzx
      mul r18.xyz, r17.xxxx, r18.xyzx
      mul r18.xyz, r20.xyzx, r18.xyzx
    else
      mov r18.xyz, l(0,0,0,0)
      mov r17.yzw, l(0,0,0,0)
    endif
  else
    mov r18.xyz, l(0,0,0,0)
    mov r17.yzw, l(0,0,0,0)
  endif
  add r15.xyz, r15.xyzx, r18.xyzx
  add r16.xyz, r16.xyzx, r17.yzwy
  iadd r12.w, r12.w, l(1)
endloop
ult r0.xy, r1.xyxx, cb0[1].zwzz
and r0.x, r0.y, r0.x
if_nz r0.x
  ld_indexable(texture2d)(float,float,float,float) r0.xyzw, r1.xyzz, t8.xyzw
  add r2.xyz, r15.xyzx, r16.xyzx
  dp3 r2.w, r15.xyzx, l(0.212600, 0.715200, 0.072200, 0.000000)
  mad r0.xyzw, r0.xyzw, cb1[128].yyyy, r2.xyzw
  mul r0.xyzw, r0.xyzw, cb1[128].xxxx
  store_uav_typed u0.xyzw, r1.xyyy, r0.xyzw
endif
ret
// Approximately 0 instruction slots used
