//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.9 on Mon Aug 31 08:54:02 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[5], immediateIndexed
dcl_constantbuffer CB1[140], immediateIndexed
dcl_constantbuffer CB2[1280], dynamicIndexed
dcl_constantbuffer CB3[1024], dynamicIndexed
dcl_constantbuffer CB4[768], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2darray (float,float,float,float) t10
dcl_resource_buffer (uint,uint,uint,uint) t11
dcl_resource_structured t12, 80
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.xy
dcl_temps 39
dcl_thread_group 16, 16, 1
ld_indexable(buffer)(uint,uint,uint,uint) r0.x, vThreadGroupID.xxxx, t11.xyzw
and r1.x, r0.x, l(255)
ushr r1.y, r0.x, l(8)
imad r0.yz, r1.xxyx, l(0, 16, 16, 0), vThreadIDInGroup.xxyx
iadd r1.xy, r0.yzyy, cb0[1].xyxx
ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r0.w, r0.x, l(0), t12.xxxx
ine r2.x, cb0[4].y, l(0)
ult r2.y, l(64), r0.w
and r2.x, r2.y, r2.x
if_nz r2.x
  store_uav_typed u0.xyzw, r1.xyyy, l(2.000000,0,0,1.000000)
  ret
endif
utof r0.yz, r0.yyzy
add r0.yz, r0.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
iadd r2.xy, -cb0[1].xyxx, cb0[1].zwzz
utof r2.xy, r2.xyxx
div r0.yz, r0.yyzy, r2.xxyx
mad r0.yz, r0.yyzy, l(0.000000, 2.000000, -2.000000, 0.000000), l(0.000000, -1.000000, 1.000000, 0.000000)
mov r1.z, l(0)
ld_indexable(texture2d)(float,float,float,float) r2.x, r1.xyzz, t5.xyzw
mad r2.y, r2.x, cb1[57].x, cb1[57].y
mad r2.x, r2.x, cb1[57].z, -cb1[57].w
rcp r2.x, r2.x
add r2.x, r2.x, r2.y
mul r0.yz, r0.yyzy, r2.xxxx
mul r3.xyzw, r0.zzzz, cb1[41].xyzw
mad r3.xyzw, r0.yyyy, cb1[40].xyzw, r3.xyzw
mad r3.xyzw, r2.xxxx, cb1[42].xyzw, r3.xyzw
add r3.xyzw, r3.xyzw, cb1[43].xyzw
div r2.yzw, r3.xxyz, r3.wwww
umin r0.w, r0.w, l(64)
ld_indexable(texture2d)(float,float,float,float) r3.xyz, r1.xyzz, t1.xyzw
ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.xyzz, t2.xyzw
ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r1.xyzz, t3.xyzw
ld_indexable(texture2d)(float,float,float,float) r6.xyz, r1.xyzz, t4.xyzw
mad r3.xyz, r3.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
dp3 r3.w, r3.xyzx, r3.xyzx
rsq r3.w, r3.w
mul r3.xyz, r3.wwww, r3.xyzx
mad r3.w, r4.w, l(255.000000), l(0.500000)
ftou r3.w, r3.w
and r7.xy, r3.wwww, l(15, 16, 0, 0)
add r3.w, -r4.x, l(1.000000)
mul r8.xyz, r5.xyzx, r3.wwww
mul r4.yw, r4.yyyz, r4.yyyz
mul r6.w, r4.y, l(0.160000)
mad r5.xyz, -r4.yyyy, l(0.160000, 0.160000, 0.160000, 0.000000), r5.xyzx
mad r5.xyz, r4.xxxx, r5.xyzx, r6.wwww
mad r8.xyz, r8.xyzx, cb1[132].wwww, cb1[132].xyzx
ieq r9.xyzw, r7.xxxx, l(1, 2, 5, 3)
or r4.xy, r9.yzyy, r9.xxxx
mad r9.xyz, r5.xyzx, cb1[133].wwww, cb1[133].xyzx
movc r5.xyz, r4.xxxx, r9.xyzx, r5.xyzx
mad r9.xyz, r5.xyzx, l(0.450000, 0.450000, 0.450000, 0.000000), r8.xyzx
movc r7.yzw, r7.yyyy, r3.wwww, r8.xxyz
utof r8.xy, r1.xyxx
add r8.xy, r8.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mul r8.xy, r8.xyxx, cb1[126].zwzz
sample_l_indexable(texture2d)(float,float,float,float) r3.w, r8.xyxx, t6.yzwx, s0, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r4.x, r8.xyxx, t7.yxzw, s1, l(0.000000)
add r8.xyz, -r2.yzwy, cb1[59].xyzx
dp3 r6.w, r8.xyzx, r8.xyzx
rsq r6.w, r6.w
mul r8.xyz, r6.wwww, r8.xyzx
ishl r1.w, cb1[139].z, l(3)
and r10.xyz, r1.xywx, l(63, 63, 63, 0)
mov r10.w, l(0)
ld_indexable(texture3d)(float,float,float,float) r10.xy, r10.xyzw, t0.xyzw
mad r10.xy, r10.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
lt r10.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r10.xxxy
lt r11.xy, r10.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
iadd r10.zw, -r10.zzzw, r11.xxxy
itof r10.zw, r10.zzzw
add r10.xy, -|r10.xyxx|, l(1.000000, 1.000000, 0.000000, 0.000000)
sqrt r10.xy, r10.xyxx
add r10.xy, -r10.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r10.xy, r10.xyxx, r10.zwzz
mul r10.xy, r10.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000)
mov r1.w, l(0)
mov r6.w, l(0)
mov r8.w, l(0)
mov r10.zw, l(0,0,0,0)
mov r11.x, l(0)
loop
  ult r11.y, r10.z, r0.w
  ult r11.z, r11.x, l(8)
  and r11.y, r11.z, r11.y
  breakc_z r11.y
  and r11.y, r10.z, l(-4)
  iadd r11.y, r11.y, l(16)
  ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r11.y, r0.x, r11.y, t12.xxxx
  bfi r11.z, l(2), l(3), r10.z, l(0)
  ushr r11.y, r11.y, r11.z
  and r11.z, r11.y, l(255)
  ge r11.w, cb2[r11.z + 0].x, l(0.000000)
  if_nz r11.w
    bfi r11.y, l(8), l(2), r11.y, l(0)
    mul r12.xyzw, r0.zzzz, cb2[r11.y + 257].xyzw
    mad r12.xyzw, r0.yyyy, cb2[r11.y + 256].xyzw, r12.xyzw
    mad r12.xyzw, r2.xxxx, cb2[r11.y + 258].xyzw, r12.xyzw
    add r12.xyzw, r12.xyzw, cb2[r11.y + 259].xyzw
    rcp r11.y, r12.w
    mul r11.yw, r11.yyyy, r12.xxxy
    add r12.x, l(1.000000), -cb2[r11.z + 0].w
    max r12.x, r12.x, l(0.000000)
    mul r12.xy, r10.xyxx, r12.xxxx
    mad r11.yw, r11.yyyw, cb0[3].xxxy, r12.xxxy
    add r11.yw, r11.yyyw, l(0.000000, -0.500000, 0.000000, -0.500000)
    round_z r12.xy, r11.ywyy
    add r11.yw, r11.yyyw, -r12.xxxy
    add r12.xy, r12.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
    mul r13.xy, r12.xyxx, cb0[3].zwzz
    mov r13.z, cb2[r11.z + 0].x
    gather4_aoffimmi_indexable(-1,-1,0)(texture2darray)(float,float,float,float) r14.xyzw, r13.xyzx, t10.xyzw, s3.x
    add r15.xyzw, -r12.zzzz, r14.xyzw
    mad_sat r15.xyzw, r15.xyzw, cb2[r11.z + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r14.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r14.xyzw
    and r14.xyzw, r14.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r14.xyzw, r14.xyzw, r15.xyzw
    min r14.xyzw, r14.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(1,-1,0)(texture2darray)(float,float,float,float) r15.xyzw, r13.xyzx, t10.xyzw, s3.x
    add r16.xyzw, -r12.zzzz, r15.xyzw
    mad_sat r16.xyzw, r16.xyzw, cb2[r11.z + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r15.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r15.xyzw
    and r15.xyzw, r15.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r15.xyzw, r15.xyzw, r16.xyzw
    min r15.xyzw, r15.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(-1,1,0)(texture2darray)(float,float,float,float) r16.xyzw, r13.xyzx, t10.xyzw, s3.x
    add r17.xyzw, -r12.zzzz, r16.xyzw
    mad_sat r17.xyzw, r17.xyzw, cb2[r11.z + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r16.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r16.xyzw
    and r16.xyzw, r16.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r16.xyzw, r16.xyzw, r17.xyzw
    min r16.xyzw, r16.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    gather4_aoffimmi_indexable(1,1,0)(texture2darray)(float,float,float,float) r13.xyzw, r13.xyzx, t10.xyzw, s3.x
    add r12.xyzw, -r12.zzzz, r13.xyzw
    mad_sat r12.xyzw, r12.xyzw, cb2[r11.z + 0].zzzz, l(1.000000, 1.000000, 1.000000, 1.000000)
    lt r13.xyzw, l(0.990000, 0.990000, 0.990000, 0.990000), r13.xyzw
    and r13.xyzw, r13.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
    add r12.xyzw, r12.xyzw, r13.xyzw
    min r12.xyzw, r12.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    add r13.xy, -r14.wxww, r15.zyzz
    mad r13.xy, r11.yyyy, r13.xyxx, r14.wxww
    add r13.xy, r14.zyzz, r13.xyxx
    add r13.xy, r15.wxww, r13.xyxx
    add r12.yz, -r16.wwxw, r12.zzyz
    mad r12.yz, r11.yyyy, r12.yyzy, r16.wwxw
    add r12.yz, r16.zzyz, r12.yyzy
    add r12.xy, r12.wxww, r12.yzyy
    add r11.y, -r13.x, r12.y
    mad r11.y, r11.w, r11.y, r13.x
    add r11.y, r13.y, r11.y
    add r11.y, r12.x, r11.y
    mad r11.y, r11.y, l(0.111111112), l(-1.000000)
    mad r11.y, cb2[r11.z + 0].y, r11.y, l(1.000000)
    lt r11.z, r11.y, l(1.000000)
    if_nz r11.z
      lt r11.z, l(0.000000), r11.y
      if_nz r11.z
        mad r11.y, r11.y, l(15.000000), l(0.500000)
        ftou r11.y, r11.y
        umin r11.y, r11.y, l(15)
        ishl r11.z, r11.x, l(2)
        ishl r11.y, r11.y, r11.z
        or r8.w, r8.w, r11.y
        bfi r6.w, l(1), r10.w, l(1), r6.w
        iadd r11.x, r11.x, l(1)
      endif
      bfi r1.w, l(1), r10.w, l(1), r1.w
    endif
    iadd r10.w, r10.w, l(1)
  endif
  iadd r10.z, r10.z, l(1)
endloop
mul r0.y, r3.w, r5.w
min r0.z, r3.w, r5.w
mad r2.x, r5.w, r3.w, l(1.000000)
add r2.x, -r0.z, r2.x
mul r2.x, r2.x, r2.x
mad r0.z, -r5.w, r3.w, r0.z
mad r0.y, r2.x, r0.z, r0.y
mul r0.z, r4.x, r0.y
min r2.x, r4.x, r0.y
mad r3.w, r0.y, r4.x, l(1.000000)
add r3.w, -r2.x, r3.w
mul r3.w, r3.w, r3.w
mad r0.y, -r0.y, r4.x, r2.x
mad r0.y, r3.w, r0.y, r0.z
dp3 r0.z, r3.xyzx, r8.xyzx
mov_sat r2.x, r0.z
mad r10.xyz, r9.xyzx, l(2.040400, 2.040400, 2.040400, 0.000000), l(-0.332400, -0.332400, -0.332400, 0.000000)
mad r11.xyz, r9.xyzx, l(-4.795100, -4.795100, -4.795100, 0.000000), l(0.641700, 0.641700, 0.641700, 0.000000)
mad r9.xyz, r9.xyzx, l(2.755200, 2.755200, 2.755200, 0.000000), l(0.690300, 0.690300, 0.690300, 0.000000)
max r12.x, r4.z, l(0.040000)
mul r3.w, r12.x, r12.x
mad r4.x, -r12.x, r12.x, l(1.000000)
max r13.x, |r0.z|, l(0.000010)
min r4.z, r13.x, l(1.000000)
mul r5.w, r0.z, r0.z
mad r10.w, r5.w, l(2.000000), l(-1.000000)
mul r11.w, r3.w, r3.w
mad r12.z, r3.w, r3.w, l(-1.000000)
mul r12.w, r11.w, l(0.318309873)
add r14.x, r4.z, r4.z
dp3 r14.y, r5.xyzx, l(0.333333343, 0.333333343, 0.333333343, 0.000000)
mul_sat r14.z, r14.y, l(50.000000)
add r15.xyz, -r5.xyzx, r14.zzzz
mad r16.xyzw, r12.xxxx, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r14.w, r16.x, r16.x
mul r15.w, r12.x, l(0.577000)
max r12.y, r15.w, l(0.040000)
dp2 r15.w, l(0.850000, 0.150000, 0.000000, 0.000000), r12.xyxx
mul r17.x, r15.w, r15.w
mad r17.y, -r15.w, r15.w, l(1.000000)
mul r18.xyz, r12.yxyy, r12.yxyy
mad r12.x, -r12.y, r12.y, l(1.000000)
mul r19.xyz, r18.xyzx, r18.xyzx
mad r17.zw, r18.yyyz, r18.yyyz, l(0.000000, 0.000000, -1.000000, -1.000000)
mul r18.yz, r19.yyzy, l(0.000000, 0.318309873, 0.318309873, 0.000000)
add r12.y, -r14.y, r14.z
mad r20.xyzw, r15.wwww, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r15.w, r20.x, r20.x
mad r19.yzw, r6.xxyz, l(0.000000, 2.000000, 2.000000, 2.000000), l(0.000000, -1.000000, -1.000000, -1.000000)
dp3 r18.w, r19.yzwy, r19.yzwy
rsq r18.w, r18.w
mul r19.yzw, r18.wwww, r19.yyzw
add r18.w, r5.x, l(-0.045500)
mul_sat r18.w, r18.w, l(249.999985)
mul r21.x, r4.z, l(-9.280000)
exp r21.x, r21.x
mad r21.x, r21.x, l(1.019200), l(0.024116)
min r21.x, r21.x, l(1.000000)
add r21.x, -r21.x, l(1.000000)
mul r21.x, r21.x, r21.x
mad r21.yzw, r0.zzzz, r3.yyzx, -r8.yyzx
dp3 r22.x, r21.yzwy, r21.yzwy
rsq r22.x, r22.x
mul r21.yzw, r21.yyzw, r22.xxxx
dp3 r22.x, r21.wyzw, r8.xyzx
ieq r22.yzw, r7.xxxx, l(0, 9, 7, 8)
max r6.z, r6.z, l(0.004000)
lt r23.xy, l(0.500000, 0.750000, 0.000000, 0.000000), r6.xxxx
movc r23.yzw, r23.yyyy, l(0,-1.000000,0,0.333333343), l(0,1.000000,1.000000,0.666666627)
mul r24.xyz, r3.xyzx, r23.yyyy
dp3 r6.x, r24.xyzx, r8.xyzx
max r7.x, |r6.x|, l(0.000010)
min r7.x, r7.x, l(1.000000)
add r6.z, r6.z, r6.z
rcp r6.z, r6.z
add r23.y, r6.z, l(1.000000)
mul r23.y, r23.y, l(0.318309873)
mov r13.yzw, l(0,1.000000,1.000000,1.000000)
mov r25.xyz, l(1.000000,0,0,0)
mov r26.zw, l(0,0,0.0795744061,0.318309873)
mov r24.w, l(0)
mov r27.xyzw, l(0,0,0,0)
mov r28.xyzw, l(0,0,0,0)
loop
  uge r29.x, r24.w, r0.w
  breakc_nz r29.x
  and r29.x, r24.w, l(-4)
  iadd r29.x, r29.x, l(16)
  ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r29.x, r0.x, r29.x, t12.xxxx
  bfi r29.y, l(2), l(3), r24.w, l(0)
  ushr r29.x, r29.x, r29.y
  and r29.x, r29.x, l(255)
  ge r29.y, cb2[r29.x + 0].x, l(0.000000)
  ult r29.z, r28.w, l(8)
  and r29.y, r29.z, r29.y
  if_nz r29.y
    ushr r29.y, r1.w, r27.w
    and r29.y, r29.y, l(1)
    ushr r29.w, r6.w, r27.w
    and r29.w, r29.w, l(1)
    ine r29.zw, r29.yyyw, l(0, 0, 0, 0)
    and r29.z, r29.w, r29.z
    if_nz r29.z
      ishl r29.z, r28.w, l(2)
      ushr r29.z, r8.w, r29.z
      and r29.z, r29.z, l(15)
      utof r29.z, r29.z
      mul r29.z, r29.z, l(0.0666666701)
      iadd r28.w, r28.w, l(1)
    else
      movc r29.z, r29.y, l(0), l(1.000000)
    endif
    iadd r27.w, r27.w, l(1)
  else
    mov r29.z, l(1.000000)
  endif
  ne r29.y, l(0.000000), cb3[r29.x + 256].w
  add r30.xyz, -r2.yzwy, cb4[r29.x + 0].xyzx
  dp3 r29.w, r30.xyzx, r30.xyzx
  rsq r30.w, r29.w
  mul r30.xyz, r30.wwww, r30.xyzx
  ne r30.w, l(0.000000), cb4[r29.x + 512].w
  if_nz r30.w
    mov r30.w, l(1.000000)
  else
    mul r31.x, cb4[r29.x + 0].w, cb4[r29.x + 0].w
    mul r31.x, r29.w, r31.x
    mad r31.x, -r31.x, r31.x, l(1.000000)
    max r31.x, r31.x, l(0.000000)
    mul r31.x, r31.x, r31.x
    add r31.y, r29.w, l(1.000000)
    mad r31.y, cb3[r29.x + 512].z, cb3[r29.x + 512].z, r31.y
    rcp r31.y, r31.y
    mul r30.w, r31.y, r31.x
  endif
  dp3 r31.x, r30.xyzx, cb3[r29.x + 0].xyzx
  add r31.x, r31.x, -cb3[r29.x + 512].x
  mul_sat r31.x, r31.x, cb3[r29.x + 512].y
  mul r31.x, r31.x, r31.x
  mul r31.x, r30.w, r31.x
  movc r29.y, r29.y, r31.x, r30.w
  lt r30.w, l(0.000000), r29.y
  if_nz r30.w
    and r30.w, l(3), cb3[r29.x + 768].x
    if_nz r30.w
      min r29.z, r0.y, r29.z
    else
      mov r29.z, r0.y
    endif
    lt r30.w, l(0.000000), r29.z
    if_nz r30.w
      dp3 r30.w, r30.xyzx, -cb3[r29.x + 0].xyzx
      lt r31.x, r30.w, l(0.000000)
      min r30.w, |r30.w|, l(1.000000)
      mad r31.y, r30.w, l(-0.0187292993), l(0.074261)
      mad r31.y, r31.y, r30.w, l(-0.212114394)
      mad r31.y, r31.y, r30.w, l(1.57072878)
      add r30.w, -r30.w, l(1.000000)
      sqrt r30.w, r30.w
      mul r30.w, r30.w, r31.y
      movc r31.y, r31.x, l(-1.000000), l(1.000000)
      and r31.x, r31.x, l(0x40490fdb)
      mad r30.w, r30.w, r31.y, r31.x
      mad r31.x, -r30.w, l(0.318309873), l(1.000000)
      utof r30.w, cb3[r29.x + 768].z
      add r30.w, r30.w, l(0.500000)
      mul r31.y, r30.w, cb0[0].w
      sample_l_indexable(texture2d)(float,float,float,float) r30.w, r31.xyxx, t8.yzwx, s2, l(0.000000)
      mul r31.xyz, r30.wwww, cb4[r29.x + 512].xyzx
      mad r32.xyz, r10.xyzx, r29.zzzz, r11.xyzx
      mad r32.xyz, r32.xyzx, r29.zzzz, r9.xyzx
      max r32.xyz, r32.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
      mul r32.xyz, r29.zzzz, r32.xyzx
      add r30.w, r2.x, r29.z
      lt r31.w, r30.w, l(0.000001)
      log r30.w, r30.w
      mul r30.w, r4.w, r30.w
      exp r30.w, r30.w
      movc r30.w, r31.w, l(0), r30.w
      add r29.z, r29.z, r30.w
      add_sat r29.z, r29.z, l(-1.000000)
      sqrt r29.w, r29.w
      max r29.w, r29.w, l(0.001000)
      div r29.x, cb3[r29.x + 512].z, r29.w
      if_nz r4.y
        mul_sat r29.w, r4.x, r29.x
        dp3 r30.w, r3.xyzx, r30.xyzx
        dp3 r31.w, r8.xyzx, r30.xyzx
        lt r32.w, l(0.000000), r29.w
        if_nz r32.w
          mad r33.x, -r29.w, r29.w, l(1.000000)
          sqrt r33.x, r33.x
          dp2 r33.y, r0.zzzz, r30.wwww
          add r33.z, -r31.w, r33.y
          lt r33.w, r33.z, r33.x
          not r34.x, r33.w
          if_nz r33.w
            mad r33.w, -r33.z, r33.z, l(1.000000)
            max r33.w, r33.w, l(0.000010)
            rsq r33.w, r33.w
            mul r33.w, r29.w, r33.w
            mad r34.y, -r33.z, r30.w, r0.z
            mul r34.z, r33.w, r34.y
            mad r33.z, -r33.z, r31.w, r10.w
            mad r34.w, -r30.w, r30.w, -r5.w
            add r34.w, r34.w, l(1.000000)
            mad r34.w, -r31.w, r31.w, r34.w
            mad_sat r33.y, r33.y, r31.w, r34.w
            sqrt r33.y, r33.y
            mul r33.yz, r33.yyzy, r33.wwww
            mul r34.w, r0.z, r33.y
            add r35.x, r34.w, r34.w
            mad r35.y, r30.w, r33.x, r0.z
            mad r33.w, r33.w, r34.y, r35.y
            mad r34.y, r31.w, r33.x, r33.z
            add r34.y, r34.y, l(1.000000)
            mul r35.zw, r33.yyyw, r34.yyyy
            mul r36.x, r33.w, r35.x
            mul r34.w, r34.w, r33.w
            mul r34.w, r34.w, l(0.500000)
            mad r34.w, r35.z, l(-0.500000), r34.w
            mad r36.y, -r35.z, l(2.000000), r36.x
            mul r36.x, r36.y, r36.x
            mad r35.z, r35.z, r35.z, r36.x
            mul r36.x, r34.y, r34.y
            mad r34.y, r31.w, r33.x, r34.y
            mad r34.y, r34.y, l(-0.500000), l(-0.500000)
            mul r34.yw, r34.yyyw, r35.wwww
            mad r34.y, r35.y, r36.x, r34.y
            mad r33.w, r33.w, r34.y, r35.z
            mul r34.y, r34.w, r34.w
            mad r35.y, r33.w, r33.w, -r34.y
            mad r35.y, r35.y, l(0.500000), r34.y
            max r35.y, r35.y, l(0.000010)
            rcp r35.y, r35.y
            mul r33.w, r33.w, r34.w
            mul r33.w, r35.y, r33.w
            min r33.w, r33.w, l(1.000000)
            max r33.w, r33.w, l(-1.000000)
            mad r34.y, -r34.y, r35.y, l(1.000000)
            max r34.y, r34.y, l(-1.000000)
            mul r33.y, r33.y, r33.w
            mad r33.y, r34.y, r34.z, r33.y
            mul r33.w, r35.x, r33.w
            mad r33.z, r34.y, r33.z, r33.w
            mad r33.y, r30.w, r33.x, r33.y
            mad r31.w, r31.w, r33.x, r33.z
          else
            mov r33.y, r30.w
          endif
        else
          mov r33.y, r30.w
          mov r34.x, l(0)
        endif
        mad r33.x, r31.w, l(2.000000), l(2.000000)
        max r33.x, r33.x, l(0.000010)
        rsq r33.x, r33.x
        add r33.y, r0.z, r33.y
        mul_sat r35.x, r33.x, r33.y
        mad_sat r35.y, r33.x, r31.w, r33.x
        movc r33.xy, r34.xxxx, r13.yxyy, r35.xyxx
        mov_sat r29.x, r29.x
        max r31.w, r30.w, l(0.000000)
        lt r31.w, r31.w, r29.x
        max r33.z, -r29.x, r30.w
        add r33.z, r29.x, r33.z
        mul r33.z, r33.z, r33.z
        mul r33.w, r29.x, l(4.000000)
        rcp r33.w, r33.w
        mul r33.z, r33.w, r33.z
        movc_sat r30.w, r31.w, r33.z, r30.w
        mul r31.w, r33.x, r33.x
        mad r31.w, r31.w, r12.z, l(1.000000)
        mul r31.w, r31.w, r31.w
        rcp r31.w, r31.w
        mul r31.w, r12.w, r31.w
        mul r33.x, r14.x, r30.w
        add r33.z, r4.z, r30.w
        mad r33.z, -r14.x, r30.w, r33.z
        mad r33.x, r3.w, r33.z, r33.x
        rcp r33.x, r33.x
        mul r33.x, r33.x, l(0.500000)
        add r33.z, -r33.y, l(1.000000)
        mul r33.w, r33.z, r33.z
        mul r33.w, r33.w, r33.w
        mul r33.z, r33.z, r33.w
        mad r34.xyz, r33.zzzz, r15.xyzx, r5.xyzx
        mul r33.z, r30.w, l(-9.280000)
        exp r33.z, r33.z
        min r33.z, r14.w, r33.z
        mad r33.z, r33.z, r16.x, r16.y
        mad r33.zw, r33.zzzz, l(0.000000, 0.000000, -1.040000, 1.040000), r16.zzzw
        mul r33.w, r14.z, r33.w
        mad_sat r33.z, r14.y, r33.z, r33.w
        add r33.z, -r33.z, l(1.000000)
        mul r33.z, r30.w, r33.z
        max r33.y, r33.y, l(0.000010)
        rcp r33.y, r33.y
        mul r33.w, r29.w, l(0.250000)
        mad r29.w, r3.w, l(3.000000), r29.w
        mul r29.w, r29.w, r33.w
        mad r29.w, r29.w, r33.y, r11.w
        rcp r29.w, r29.w
        mul r29.w, r11.w, r29.w
        movc r29.w, r32.w, r29.w, l(1.000000)
        mul r30.w, r30.w, r31.w
        mul r30.w, r33.x, r30.w
        mul r33.xyw, r34.xyxz, r30.wwww
        mul r33.xyw, r29.wwww, r33.xyxw
        mul r29.w, r33.z, l(0.318309873)
        mul r34.xyz, r7.yzwy, r29.wwww
      else
        if_nz r9.w
          mul_sat r29.w, r17.y, r29.x
          dp3 r30.w, r3.xyzx, r30.xyzx
          dp3 r31.w, r8.xyzx, r30.xyzx
          lt r32.w, l(0.000000), r29.w
          if_nz r32.w
            mad r32.w, -r29.w, r29.w, l(1.000000)
            sqrt r32.w, r32.w
            dp2 r33.z, r0.zzzz, r30.wwww
            add r34.w, -r31.w, r33.z
            lt r35.x, r34.w, r32.w
            not r35.y, r35.x
            if_nz r35.x
              mad r35.x, -r34.w, r34.w, l(1.000000)
              max r35.x, r35.x, l(0.000010)
              rsq r35.x, r35.x
              mul r29.w, r29.w, r35.x
              mad r35.x, -r34.w, r30.w, r0.z
              mul r35.z, r29.w, r35.x
              mad r34.w, -r34.w, r31.w, r10.w
              mul r34.w, r29.w, r34.w
              mad r35.w, -r30.w, r30.w, -r5.w
              add r35.w, r35.w, l(1.000000)
              mad r35.w, -r31.w, r31.w, r35.w
              mad_sat r33.z, r33.z, r31.w, r35.w
              sqrt r33.z, r33.z
              mul r33.z, r29.w, r33.z
              mul r35.w, r0.z, r33.z
              add r36.x, r35.w, r35.w
              mad r36.y, r30.w, r32.w, r0.z
              mad r29.w, r29.w, r35.x, r36.y
              mad r35.x, r31.w, r32.w, r34.w
              add r35.x, r35.x, l(1.000000)
              mul r36.z, r33.z, r35.x
              mul r36.w, r29.w, r35.x
              mul r37.x, r29.w, r36.x
              mul r35.w, r35.w, r29.w
              mul r35.w, r35.w, l(0.500000)
              mad r35.w, r36.z, l(-0.500000), r35.w
              mad r37.y, -r36.z, l(2.000000), r37.x
              mul r37.x, r37.y, r37.x
              mad r36.z, r36.z, r36.z, r37.x
              mul r37.x, r35.x, r35.x
              mad r35.x, r31.w, r32.w, r35.x
              mad r35.x, r35.x, l(-0.500000), l(-0.500000)
              mul r35.xw, r35.xxxw, r36.wwww
              mad r35.x, r36.y, r37.x, r35.x
              mad r29.w, r29.w, r35.x, r36.z
              mul r35.x, r35.w, r35.w
              mad r36.y, r29.w, r29.w, -r35.x
              mad r36.y, r36.y, l(0.500000), r35.x
              max r36.y, r36.y, l(0.000010)
              rcp r36.y, r36.y
              mul r29.w, r29.w, r35.w
              mul r29.w, r36.y, r29.w
              min r29.w, r29.w, l(1.000000)
              max r29.w, r29.w, l(-1.000000)
              mad r35.x, -r35.x, r36.y, l(1.000000)
              max r35.x, r35.x, l(-1.000000)
              mul r33.z, r33.z, r29.w
              mad r33.z, r35.x, r35.z, r33.z
              mul r29.w, r36.x, r29.w
              mad r29.w, r35.x, r34.w, r29.w
              mad r33.z, r30.w, r32.w, r33.z
              mad r31.w, r31.w, r32.w, r29.w
            else
              mov r33.z, r30.w
            endif
          else
            mov r33.z, r30.w
            mov r35.y, l(0)
          endif
          mad r29.w, r31.w, l(2.000000), l(2.000000)
          max r29.w, r29.w, l(0.000010)
          rsq r29.w, r29.w
          add r32.w, r0.z, r33.z
          mul_sat r36.x, r29.w, r32.w
          mad_sat r36.y, r29.w, r31.w, r29.w
          movc r35.xy, r35.yyyy, r13.zxzz, r36.xyxx
          mov_sat r29.w, r29.x
          max r31.w, r30.w, l(0.000000)
          lt r31.w, r31.w, r29.w
          max r32.w, -r29.w, r30.w
          add r32.w, r29.w, r32.w
          mul r32.w, r32.w, r32.w
          mul r29.w, r29.w, l(4.000000)
          rcp r29.w, r29.w
          mul r29.w, r29.w, r32.w
          movc_sat r29.w, r31.w, r29.w, r30.w
          mul_sat r30.w, r4.x, r29.x
          max r31.w, r35.y, l(0.000010)
          rcp r31.w, r31.w
          lt r32.w, l(0.000000), r30.w
          mul r33.z, r30.w, l(0.250000)
          mad r30.w, r3.w, l(3.000000), r30.w
          mul r30.w, r30.w, r33.z
          mad r30.w, r30.w, r31.w, r11.w
          rcp r30.w, r30.w
          mul r30.w, r11.w, r30.w
          movc r36.x, r32.w, r30.w, l(1.000000)
          mul_sat r30.w, r12.x, r29.x
          lt r32.w, l(0.000000), r30.w
          mul r33.z, r30.w, l(0.250000)
          mad r30.w, r18.x, l(3.000000), r30.w
          mul r30.w, r30.w, r33.z
          mad r30.w, r30.w, r31.w, r19.x
          rcp r30.w, r30.w
          mul r30.w, r19.x, r30.w
          movc r36.y, r32.w, r30.w, l(1.000000)
          mul r30.w, r35.x, r35.x
          mad r35.xz, r30.wwww, r17.zzwz, l(1.000000, 0.000000, 1.000000, 0.000000)
          mul r35.xz, r35.xxzx, r35.xxzx
          rcp r35.xz, r35.xxzx
          mul r35.xz, r18.yyzy, r35.xxzx
          mul r30.w, r14.x, r29.w
          add r31.w, r4.z, r29.w
          mad r31.w, -r14.x, r29.w, r31.w
          mad r30.w, r17.x, r31.w, r30.w
          rcp r30.w, r30.w
          mul r30.w, r29.w, r30.w
          add r31.w, -r35.y, l(1.000000)
          mul r32.w, r31.w, r31.w
          mul r32.w, r32.w, r32.w
          mul r31.w, r31.w, r32.w
          mad r31.w, r31.w, r12.y, r14.y
          mul r32.w, r29.w, l(-9.280000)
          exp r32.w, r32.w
          min r32.w, r15.w, r32.w
          mad r32.w, r32.w, r20.x, r20.y
          mad r35.yw, r32.wwww, l(0.000000, -1.040000, 0.000000, 1.040000), r20.zzzw
          mad_sat r32.w, r35.y, l(0.032500), r35.w
          add r32.w, -r32.w, l(1.000000)
          mul r29.w, r29.w, r32.w
          mul r30.w, r30.w, r31.w
          mul r30.w, r30.w, l(0.500000)
          mul r35.xy, r35.xzxx, r36.xyxx
          dp2 r31.w, l(0.850000, 0.150000, 0.000000, 0.000000), r35.xyxx
          mul r33.xyw, r30.wwww, r31.wwww
          mul r29.w, r29.w, l(0.318309873)
          mul r34.xyz, r7.yzwy, r29.wwww
        else
          if_nz r22.y
            mul_sat r29.w, r4.x, r29.x
            dp3 r30.w, r3.xyzx, r30.xyzx
            dp3 r31.w, r8.xyzx, r30.xyzx
            lt r32.w, l(0.000000), r29.w
            if_nz r32.w
              mad r33.z, -r29.w, r29.w, l(1.000000)
              sqrt r33.z, r33.z
              dp2 r34.w, r0.zzzz, r30.wwww
              add r35.x, -r31.w, r34.w
              lt r35.y, r35.x, r33.z
              not r35.z, r35.y
              if_nz r35.y
                mad r35.y, -r35.x, r35.x, l(1.000000)
                max r35.y, r35.y, l(0.000010)
                rsq r35.y, r35.y
                mul r35.y, r29.w, r35.y
                mad r35.w, -r35.x, r30.w, r0.z
                mul r36.x, r35.w, r35.y
                mad r35.x, -r35.x, r31.w, r10.w
                mul r35.x, r35.x, r35.y
                mad r36.y, -r30.w, r30.w, -r5.w
                add r36.y, r36.y, l(1.000000)
                mad r36.y, -r31.w, r31.w, r36.y
                mad_sat r34.w, r34.w, r31.w, r36.y
                sqrt r34.w, r34.w
                mul r34.w, r34.w, r35.y
                mul r36.y, r0.z, r34.w
                add r36.z, r36.y, r36.y
                mad r36.w, r30.w, r33.z, r0.z
                mad r35.y, r35.y, r35.w, r36.w
                mad r35.w, r31.w, r33.z, r35.x
                add r35.w, r35.w, l(1.000000)
                mul r37.x, r34.w, r35.w
                mul r37.y, r35.w, r35.y
                mul r37.z, r35.y, r36.z
                mul r36.y, r36.y, r35.y
                mul r36.y, r36.y, l(0.500000)
                mad r36.y, r37.x, l(-0.500000), r36.y
                mul r36.y, r36.y, r37.y
                mad r37.w, -r37.x, l(2.000000), r37.z
                mul r37.z, r37.w, r37.z
                mad r37.x, r37.x, r37.x, r37.z
                mul r37.z, r35.w, r35.w
                mad r35.w, r31.w, r33.z, r35.w
                mad r35.w, r35.w, l(-0.500000), l(-0.500000)
                mul r35.w, r35.w, r37.y
                mad r35.w, r36.w, r37.z, r35.w
                mad r35.y, r35.y, r35.w, r37.x
                mul r35.w, r36.y, r36.y
                mad r36.w, r35.y, r35.y, -r35.w
                mad r36.w, r36.w, l(0.500000), r35.w
                max r36.w, r36.w, l(0.000010)
                rcp r36.w, r36.w
                mul r35.y, r35.y, r36.y
                mul r35.y, r36.w, r35.y
                min r35.y, r35.y, l(1.000000)
                mad r35.w, -r35.w, r36.w, l(1.000000)
                max r35.yw, r35.yyyw, l(0.000000, -1.000000, 0.000000, -1.000000)
                mul r34.w, r34.w, r35.y
                mad r34.w, r35.w, r36.x, r34.w
                mul r35.y, r36.z, r35.y
                mad r35.x, r35.w, r35.x, r35.y
                mad r34.w, r30.w, r33.z, r34.w
                mad r31.w, r31.w, r33.z, r35.x
              else
                mov r34.w, r30.w
              endif
            else
              mov r34.w, r30.w
              mov r35.z, l(0)
            endif
            mad r33.z, r31.w, l(2.000000), l(2.000000)
            max r33.z, r33.z, l(0.000010)
            rsq r33.z, r33.z
            add r34.w, r0.z, r34.w
            mul_sat r35.x, r33.z, r34.w
            mad_sat r35.y, r33.z, r31.w, r33.z
            movc r35.xy, r35.zzzz, r13.wxww, r35.xyxx
            mov_sat r29.x, r29.x
            max r31.w, r30.w, l(0.000000)
            lt r31.w, r31.w, r29.x
            max r33.z, -r29.x, r30.w
            add r33.z, r29.x, r33.z
            mul r33.z, r33.z, r33.z
            mul r34.w, r29.x, l(4.000000)
            rcp r34.w, r34.w
            mul r33.z, r33.z, r34.w
            movc_sat r30.w, r31.w, r33.z, r30.w
            dp3_sat r31.w, r19.yzwy, r30.xyzx
            mul r33.z, r35.x, r35.x
            mad r33.z, r33.z, r12.z, l(1.000000)
            mul r33.z, r33.z, r33.z
            rcp r33.z, r33.z
            mul r33.z, r12.w, r33.z
            mul r34.w, r14.x, r30.w
            add r35.x, r4.z, r30.w
            mad r35.x, -r14.x, r30.w, r35.x
            mad r34.w, r3.w, r35.x, r34.w
            rcp r34.w, r34.w
            mul r34.w, r34.w, l(0.500000)
            add r35.x, -r35.y, l(1.000000)
            mul r35.z, r35.x, r35.x
            mul r35.z, r35.z, r35.z
            mul r35.x, r35.x, r35.z
            mad r35.x, r35.x, l(0.954500), l(0.045500)
            mul r35.z, r31.w, r31.w
            mad r35.z, r35.z, l(-0.750000), l(1.000000)
            mul r35.z, r35.z, r35.z
            rcp r35.z, r35.z
            mad r35.z, r35.z, l(0.0795774609), l(-0.318309873)
            mad r35.z, r18.w, r35.z, l(0.318309873)
            mul r35.w, r31.w, l(-9.280000)
            exp r35.w, r35.w
            min r35.w, r14.w, r35.w
            mad r35.w, r35.w, r16.x, r16.y
            mad r36.xy, r35.wwww, l(-1.040000, 1.040000, 0.000000, 0.000000), r16.zwzz
            mad_sat r35.w, r36.x, l(0.025500), r36.y
            add r35.w, -r35.w, l(1.000000)
            mul r35.z, r35.w, r35.z
            mul r35.z, r21.x, r35.z
            max r35.y, r35.y, l(0.000010)
            rcp r35.y, r35.y
            mul r35.w, r29.w, l(0.250000)
            mad r29.w, r3.w, l(3.000000), r29.w
            mul r29.w, r29.w, r35.w
            mad r29.w, r29.w, r35.y, r11.w
            rcp r29.w, r29.w
            mul r29.w, r11.w, r29.w
            movc r29.w, r32.w, r29.w, l(1.000000)
            mul r30.w, r30.w, r33.z
            mul r30.w, r34.w, r30.w
            mul r30.w, r35.x, r30.w
            mul r33.xyw, r29.wwww, r30.wwww
            mul r29.w, r31.w, r35.z
            mul r34.xyz, r7.yzwy, r29.wwww
          else
            if_nz r22.z
              mul_sat r29.w, r4.x, r29.x
              dp3 r30.w, r19.yzwy, r30.xyzx
              dp3 r35.y, r8.xyzx, r30.xyzx
              dp3 r31.w, r21.wyzw, r30.xyzx
              mad r36.xyz, -r21.zwyz, r31.wwww, r30.zxyz
              dp3 r32.w, r36.xyzx, r36.xyzx
              rsq r32.w, r32.w
              mul r36.xyz, r32.wwww, r36.xyzx
              dp3 r32.w, r3.zxyz, r36.xyzx
              dp3 r35.x, r36.yzxy, r30.xyzx
              dp3 r33.z, r36.yzxy, r8.xyzx
              mul r37.xyz, r21.yzwy, r36.xyzx
              mad r36.xyz, r36.zxyz, r21.zwyz, -r37.xyzx
              dp3 r34.w, r36.xyzx, r36.xyzx
              rsq r34.w, r34.w
              mul r36.xyz, r34.wwww, r36.xyzx
              dp3 r34.w, r36.xyzx, r8.xyzx
              dp3 r35.z, r36.xyzx, r30.xyzx
              max r25.w, |r33.z|, l(0.000010)
              lt r35.w, l(0.000000), r29.w
              if_nz r35.w
                mad r36.x, -r29.w, r29.w, l(1.000000)
                sqrt r36.x, r36.x
                dp2 r36.y, r33.zzzz, r35.xxxx
                add r36.y, -r35.y, r36.y
                lt r36.z, r36.y, r36.x
                not r36.w, r36.z
                mad r37.x, -r36.y, r36.y, l(1.000000)
                max r37.x, r37.x, l(0.000010)
                rsq r37.x, r37.x
                mul r37.x, r29.w, r37.x
                mad r37.y, -r36.y, r35.x, r33.z
                dp2 r37.z, r33.zzzz, r33.zzzz
                add r37.z, r37.z, l(-1.000000)
                mad r36.y, -r36.y, r35.y, r37.z
                mul r37.zw, r35.xxxy, r36.xxxx
                mad r38.x, r37.x, r37.y, r37.z
                mad r38.y, r37.x, r36.y, r37.w
                movc r36.xy, r36.zzzz, r38.xyxx, r35.xyxx
              else
                mov r36.xy, r35.xyxx
                mov r36.w, l(0)
              endif
              mad r36.z, r36.y, l(2.000000), l(2.000000)
              max r36.z, r36.z, l(0.000010)
              rsq r36.z, r36.z
              add r36.x, r33.z, r36.x
              mul r37.x, r36.z, r36.x
              add r36.x, r22.x, r31.w
              mul r37.y, r36.z, r36.x
              add r34.w, r34.w, r35.z
              mul r37.z, r36.z, r34.w
              mad_sat r37.w, r36.z, r36.y, r36.z
              movc r37.xyzw, r36.wwww, r25.xyzw, r37.xyzw
              mad r35.z, r35.y, l(2.000000), l(2.000000)
              max r35.z, r35.z, l(0.000010)
              rsq r35.z, r35.z
              add r33.z, r35.x, r33.z
              mul r33.z, r35.z, r33.z
              mul r36.x, r35.z, r36.x
              mul r34.w, r34.w, r35.z
              min r25.w, r25.w, l(1.000000)
              mov_sat r29.x, r29.x
              max r35.z, r35.x, l(0.000000)
              lt r35.z, r35.z, r29.x
              max r36.y, -r29.x, r35.x
              add r36.y, r29.x, r36.y
              mul r36.y, r36.y, r36.y
              mul r36.z, r29.x, l(4.000000)
              rcp r36.z, r36.z
              mul r36.y, r36.z, r36.y
              movc_sat r35.x, r35.z, r36.y, r35.x
              mul r35.z, r30.w, r30.w
              mul r35.z, r35.z, l(-12.000000)
              exp r35.z, r35.z
              mad r31.w, -r31.w, r31.w, l(1.000000)
              mul r31.w, r31.w, r31.w
              mul r31.w, r31.w, r35.z
              mov_sat r30.w, -r30.w
              mad r30.w, -r30.w, r30.w, l(1.000000)
              lt r35.z, r30.w, l(0.000001)
              log r30.w, r30.w
              mul r30.w, r30.w, l(24.000000)
              exp r30.w, r30.w
              movc r30.w, r35.z, l(0), r30.w
              mad r36.yzw, r10.xxyz, r30.wwww, r11.xxyz
              mad r36.yzw, r36.yyzw, r30.wwww, r9.xxyz
              max r36.yzw, r36.yyzw, l(0.000000, 1.000000, 1.000000, 1.000000)
              mul r36.yzw, r30.wwww, r36.yyzw
              add r30.w, -r37.w, l(1.000000)
              mul r35.z, r30.w, r30.w
              mul r35.z, r35.z, r35.z
              mul r30.w, r30.w, r35.z
              mad r30.w, r30.w, l(0.953480), l(0.046520)
              dp2 r35.z, r35.xxxx, r25.wwww
              add r25.w, r25.w, r35.x
              add r25.w, -r35.z, r25.w
              mad r25.w, r3.w, r25.w, r35.z
              rcp r25.w, r25.w
              mul r25.w, r25.w, l(0.500000)
              mul r37.xyz, r37.yzxy, r37.yzxy
              mul r37.xy, r37.xyxx, l(2.857143, 0.350000, 0.000000, 0.000000)
              add r35.z, r37.y, r37.x
              mad r35.z, r37.z, r11.w, r35.z
              mul r35.z, r35.z, r35.z
              rcp r35.z, r35.z
              mul r37.x, r12.w, r35.z
              mul r35.z, r36.x, r36.x
              mul r34.w, r34.w, r34.w
              mul r34.w, r34.w, l(0.350000)
              mad r34.w, r35.z, l(2.857143), r34.w
              mul r33.z, r33.z, r33.z
              mad r38.xy, r33.zzzz, l(0.249990374, 1.000000, 0.000000, 0.000000), r34.wwww
              mul r38.xy, r38.xyxx, r38.xyxx
              rcp r37.yz, r38.xxyx
              max r33.z, r37.w, l(0.000010)
              rcp r33.z, r33.z
              mul r34.w, r29.w, l(0.250000)
              mad r29.w, r3.w, l(3.000000), r29.w
              mul r29.w, r29.w, r34.w
              mad r29.w, r29.w, r33.z, r11.w
              rcp r29.w, r29.w
              mul r29.w, r11.w, r29.w
              movc r26.x, r35.w, r29.w, l(1.000000)
              add r29.w, r32.w, l(1.000000)
              mul_sat r26.y, r29.w, l(0.392699093)
              mad r38.xyz, r10.xyzx, r35.xxxx, r11.xyzx
              mad r38.xyz, r38.xyzx, r35.xxxx, r9.xyzx
              max r38.xyz, r38.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
              mul r38.xyz, r35.xxxx, r38.xyzx
              mad r29.w, -r35.y, l(-1.800000), l(1.810000)
              lt r32.w, r29.w, l(0.000001)
              log r29.w, |r29.w|
              mul r29.w, r29.w, l(-1.500000)
              exp r29.w, r29.w
              movc r29.w, r32.w, l(0), r29.w
              mad r32.w, r35.y, r35.y, l(1.000000)
              mul r29.w, r29.w, r32.w
              mul r35.yzw, r37.xxyz, r26.xxyy
              mul r26.xy, r26.ywyy, r35.ywyy
              mul r26.x, r35.x, r26.x
              mul r26.x, r30.w, r26.x
              mul r26.x, r25.w, r26.x
              mad r29.w, r29.w, l(0.00807102676), -r26.y
              mul r29.w, r29.w, r31.w
              mad r26.y, r29.w, l(0.500000), r26.y
              mad r29.w, r35.z, r26.z, -r26.y
              mad r26.y, r29.w, l(0.150000), r26.y
              mul r35.xyz, r38.xyzx, r26.yyyy
              mad r25.w, -r30.w, r25.w, l(1.000000)
              max r25.w, r25.w, l(0.000000)
              mul r35.xyz, r25.wwww, r35.xyzx
              mul r35.xyz, r7.yzwy, r35.xyzx
              mul r33.xyw, r36.yzyw, r26.xxxx
              mul r34.xyz, r36.yzwy, r35.xyzx
            else
              if_nz r22.w
                dp3 r25.w, r24.xyzx, r30.xyzx
                dp3 r26.x, r8.xyzx, r30.xyzx
                mad r26.y, r26.x, l(2.000000), l(2.000000)
                max r26.y, r26.y, l(0.000010)
                rsq r26.y, r26.y
                add r29.w, r6.x, r25.w
                mul_sat r29.w, r26.y, r29.w
                mad_sat r26.x, r26.y, r26.x, r26.y
                mov_sat r29.x, r29.x
                max r26.y, r25.w, l(0.000000)
                lt r26.y, r26.y, r29.x
                max r30.x, r25.w, -r29.x
                add r30.x, r29.x, r30.x
                mul r30.x, r30.x, r30.x
                mul r29.x, r29.x, l(4.000000)
                rcp r29.x, r29.x
                mul r29.x, r29.x, r30.x
                movc_sat r25.w, r26.y, r29.x, r25.w
                mad r26.y, -r29.w, r29.w, l(1.000000)
                max r26.y, r26.y, l(0.00781250000)
                log r26.y, r26.y
                mul r26.y, r6.z, r26.y
                exp r26.y, r26.y
                mul r29.x, r23.y, r26.y
                add r29.w, r7.x, r25.w
                mad r29.w, -r25.w, r7.x, r29.w
                rcp r29.w, r29.w
                mul r29.w, r29.w, l(0.250000)
                add r26.x, -r26.x, l(1.000000)
                mul r30.x, r26.x, r26.x
                mul r30.x, r30.x, r30.x
                mul r26.x, r26.x, r30.x
                mad r30.xyz, r26.xxxx, r15.xyzx, r5.xyzx
                mad r26.x, r26.x, r12.y, r14.y
                add r26.x, -r26.x, l(1.000000)
                max r26.x, r26.x, l(0.000000)
                mul r29.x, r25.w, r29.x
                mul r29.x, r29.w, r29.x
                mul r30.xyz, r30.xyzx, r29.xxxx
                mul r25.w, r25.w, r26.x
                mad r26.x, r23.y, r26.y, l(-0.318309873)
                mad r26.x, r6.y, r26.x, l(0.318309873)
                mul r25.w, r25.w, r26.x
                mul r35.xyz, r7.yzwy, r25.wwww
                mul r36.xyz, r23.zzzz, r30.xyzx
                mul r37.xyz, r23.wwww, r35.xyzx
                movc r34.xyz, r23.xxxx, r37.xyzx, r35.xyzx
                movc r33.xyw, r23.xxxx, r36.xyxz, r30.xyxz
              else
                mov r34.xyz, l(0,0,0,0)
                mov r33.xyw, l(0,0,0,0)
              endif
            endif
          endif
        endif
      endif
      mul r30.xyz, r31.xyzx, r33.xywx
      mul r30.xyz, r29.yyyy, r30.xyzx
      mul r29.xzw, r29.zzzz, r30.xxyz
      mul r30.xyz, r31.xyzx, r34.xyzx
      mul r30.xyz, r29.yyyy, r30.xyzx
      mul r30.xyz, r32.xyzx, r30.xyzx
    else
      mov r30.xyz, l(0,0,0,0)
      mov r29.xzw, l(0,0,0,0)
    endif
  else
    mov r30.xyz, l(0,0,0,0)
    mov r29.xzw, l(0,0,0,0)
  endif
  add r27.xyz, r27.xyzx, r30.xyzx
  add r28.xyz, r28.xyzx, r29.xzwx
  iadd r24.w, r24.w, l(1)
endloop
ult r0.xy, r1.xyxx, cb0[1].zwzz
and r0.x, r0.y, r0.x
if_nz r0.x
  ld_indexable(texture2d)(float,float,float,float) r0.xyzw, r1.xyzz, t9.xyzw
  add r2.xyz, r27.xyzx, r28.xyzx
  dp3 r2.w, r27.xyzx, l(0.212600, 0.715200, 0.072200, 0.000000)
  mad r0.xyzw, r0.xyzw, cb1[128].yyyy, r2.xyzw
  mul r0.xyzw, r0.xyzw, cb1[128].xxxx
  store_uav_typed u0.xyzw, r1.xyyy, r0.xyzw
endif
ret
// Approximately 0 instruction slots used
