[CmdletBinding()]
param(
    [string]$RuntimeRoot = 'C:\Games\Final.Fantasy.VII.Remake.Intergrade-InsaneRamZes\End\Binaries\Win64',
    [string]$OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) ('artifacts\shader-header-audits\' + [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss-fff')))
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$shaderFixes = Join-Path $RuntimeRoot 'ShaderFixes'
$shaderCache = Join-Path $RuntimeRoot 'ShaderCache'
if (-not (Test-Path -LiteralPath $shaderFixes -PathType Container)) { throw "ShaderFixes missing: $shaderFixes" }
if (-not (Test-Path -LiteralPath $shaderCache -PathType Container)) { throw "ShaderCache missing: $shaderCache" }

$records = foreach ($file in Get-ChildItem -LiteralPath $shaderFixes -File -Filter '*.txt' | Sort-Object Name) {
    if ($file.Name -notmatch '^(?<hash>[0-9A-Fa-f]{16})-(?<stage>vs|ps|cs|gs|hs|ds)(?<hlsl>_replace)?\.txt$') {
        [pscustomobject][ordered]@{
            file = $file.Name
            status = 'unrecognized-filename'
            format = 'unknown'
            contentSha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash
        }
        continue
    }
    $hash = $Matches.hash.ToLowerInvariant()
    $stage = $Matches.stage.ToLowerInvariant()
    $isHlsl = -not [string]::IsNullOrEmpty([string]$Matches['hlsl'])
    $text = Get-Content -Raw -LiteralPath $file.FullName
    $originalBinary = Join-Path $shaderCache "$hash-$stage.bin"
    $originalExists = Test-Path -LiteralPath $originalBinary -PathType Leaf
    if ($isHlsl) {
        $headerValid = $text.StartsWith('// ---- Created with 3Dmigoto ', [StringComparison]::Ordinal) -and
            $text.Contains('// 3Dmigoto declarations') -and
            $text -match '(?m)^void main\('
        $format = '3dmigoto-decompiled-hlsl'
        $requiredHeader = '3Dmigoto created-with header and declaration block'
    } else {
        $headerValid = $text -match 'Generated by Microsoft \(R\) D3D Shader Disassembler' -and
            $text -match "(?m)^${stage}_5_0\s*$"
        $format = 'dxbc-assembly'
        $requiredHeader = 'Microsoft D3D disassembler signature/resource header and stage profile'
    }
    $status = if (-not $headerValid) { 'missing-format-appropriate-header' } elseif (-not $originalExists) { 'missing-original-binary-peer' } else { 'passed' }
    [pscustomobject][ordered]@{
        file = $file.Name
        shader = "$hash-$stage"
        stage = $stage
        format = $format
        requiredHeader = $requiredHeader
        headerValid = $headerValid
        contentSha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash
        originalBinary = if ($originalExists) { $originalBinary } else { $null }
        originalBinarySha256 = if ($originalExists) { (Get-FileHash -Algorithm SHA256 -LiteralPath $originalBinary).Hash } else { $null }
        status = $status
    }
}

$failed = @($records | Where-Object status -ne 'passed')
$manifest = [ordered]@{
    schemaVersion = 1
    generatedAtUtc = [DateTime]::UtcNow.ToString('o')
    runtimeRoot = $RuntimeRoot
    result = if ($failed.Count) { 'failed' } else { 'passed' }
    total = @($records).Count
    assembly = @($records | Where-Object format -eq 'dxbc-assembly').Count
    decompiledHlsl = @($records | Where-Object format -eq '3dmigoto-decompiled-hlsl').Count
    failures = $failed.Count
    interpretation = 'Assembly replacements retain the full disassembler header. Decompiled-HLSL replacements retain their native 3Dmigoto source header and are pinned to the exact original ShaderCache binary; assembly declarations must not be pasted into HLSL.'
    shaders = @($records)
}
[IO.Directory]::CreateDirectory($OutputDirectory) | Out-Null
$manifestPath = Join-Path $OutputDirectory 'manifest.json'
[IO.File]::WriteAllText($manifestPath, (($manifest | ConvertTo-Json -Depth 8) + [Environment]::NewLine), [Text.UTF8Encoding]::new($false))
if ($failed.Count) {
    $failed | Format-Table file,format,status -AutoSize | Out-String | Write-Host
    throw "Live shader header audit failed for $($failed.Count) file(s). Manifest: $manifestPath"
}
Write-Host "PASS: $($manifest.total) live shader replacements have format-appropriate headers and exact original binary peers ($($manifest.assembly) ASM, $($manifest.decompiledHlsl) HLSL). Manifest: $manifestPath"
