[CmdletBinding()]
param(
    [string]$OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts\native-shadow-62b-filter-test-20260901-v1'),
    [string]$BaselineAssembly = (Join-Path (Split-Path -Parent $PSScriptRoot) 'working-code\Frustum Fix\20260831-v1\accepted-runtime\ShaderFixes\62b33a2d1e505241-cs.txt'),
    [string]$OriginalHeaderAssembly = (Join-Path (Split-Path -Parent $PSScriptRoot) 'working-code\Contact shadows - Rebirth Mod - Code worked\original-remake\62b33a2d1e505241-cs.asm'),
    [string]$OriginalBinary = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts\validation-captures\ff7r-contact-area-baseline-20260831\dxbc\62b33a2d1e505241-cs.bin'),
    [string]$AssemblerPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts\shader-assembler-build\bin\cmd_Decompiler.exe')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$utf8 = [Text.UTF8Encoding]::new($false)
$newline = [Environment]::NewLine
$repo = Split-Path -Parent $PSScriptRoot

$baseline = (Resolve-Path -LiteralPath $BaselineAssembly -ErrorAction Stop).Path
$headerSource = (Resolve-Path -LiteralPath $OriginalHeaderAssembly -ErrorAction Stop).Path
$original = (Resolve-Path -LiteralPath $OriginalBinary -ErrorAction Stop).Path
$assembler = (Resolve-Path -LiteralPath $AssemblerPath -ErrorAction Stop).Path
$output = [IO.Path]::GetFullPath($OutputDirectory)

$expectedBaselineSha256 = 'A381CB443608CA44528B20C8BE6657B74FC2A7AB340C4C0E23282780A17A8D3D'
$expectedHeaderSha256 = '8A7D1C4F804A8FADE9D0ADDC317EF637B907A8B14C011461D11AD87E8565F651'
$expectedOriginalSha256 = '1E290F68B5A07E8987A674384B955C0D6A8246A96B47506CD2E4CC6E6EED9551'
if ((Get-FileHash -Algorithm SHA256 -LiteralPath $baseline).Hash -ne $expectedBaselineSha256) {
    throw 'Accepted //Frustum Fix 62b baseline fingerprint changed.'
}
if ((Get-FileHash -Algorithm SHA256 -LiteralPath $headerSource).Hash -ne $expectedHeaderSha256) {
    throw 'Authoritative 62b disassembler header fingerprint changed.'
}
if ((Get-FileHash -Algorithm SHA256 -LiteralPath $original).Hash -ne $expectedOriginalSha256) {
    throw 'Captured original 62b DXBC fingerprint changed.'
}
if (Test-Path -LiteralPath $output) {
    throw "Output already exists; refusing to merge test state: $output"
}

function Invoke-Assembler {
    param([string[]]$Arguments, [string]$LogPath)
    $messages = & $assembler @Arguments 2>&1
    $exitCode = $LASTEXITCODE
    [IO.File]::WriteAllText($LogPath, ($messages | Out-String), $utf8)
    if ($exitCode -ne 0) { throw "Shader assembly failed; see $LogPath" }
}

$validation = Join-Path $output 'validation'
$payloadMods = Join-Path $output 'payload\Mods'
$payloadShaders = Join-Path $output 'payload\ShaderFixes'
foreach ($directory in @($validation, $payloadMods, $payloadShaders)) {
    [IO.Directory]::CreateDirectory($directory) | Out-Null
}

$source = [IO.File]::ReadAllText($baseline)
$headerLines = @(Get-Content -LiteralPath $headerSource)
$headerProfile = [array]::IndexOf($headerLines,'cs_5_0')
if ($headerProfile -lt 1) { throw 'Authoritative 62b header source is incomplete.' }
$header = @($headerLines[0..($headerProfile - 1)])
$headerText = $header -join $newline
if ($headerText -notmatch 'Generated by Microsoft \(R\) D3D Shader Disassembler' -or
    $headerText -notmatch 'using 3Dmigoto' -or $headerText -notmatch 'Input signature:' -or
    $headerText -notmatch 'Output signature:') { throw 'Authoritative 62b header is incomplete.' }
foreach ($required in @('dcl_resource_texture1d (float,float,float,float) t120', 'dcl_temps 40')) {
    if ($source -notmatch [regex]::Escape($required)) { throw "Accepted baseline is missing: $required" }
}
if ($source -match 'Native Shadow Filter Test') { throw 'Accepted baseline already contains this experiment.' }

$firstAnchor = 'mov r12.z, cb2[r10.y + 0].x'
$secondAnchor = 'gather4_aoffimmi_indexable(1,-1,0)(texture2darray)(float,float,float,float) r14.xyzw, r12.xyzx, t9.xyzw, s3.x'
$thirdAnchor = 'gather4_aoffimmi_indexable(-1,1,0)(texture2darray)(float,float,float,float) r15.xyzw, r12.xyzx, t9.xyzw, s3.x'
$fourthAnchor = 'gather4_aoffimmi_indexable(1,1,0)(texture2darray)(float,float,float,float) r12.xyzw, r12.xyzx, t9.xyzw, s3.x'
foreach ($anchor in @($firstAnchor,$secondAnchor,$thirdAnchor,$fourthAnchor)) {
    if ([regex]::Matches($source,[regex]::Escape($anchor)).Count -ne 1) { throw "Expected one native PCF anchor: $anchor" }
}

$modified = $source.Replace(
    $firstAnchor,
    $firstAnchor + $newline +
    '// Native Shadow Filter Test: Page Up expands the four native PCF gather corners.' + $newline +
    'ld_indexable(texture1d)(float,float,float,float) r24.x, l(28, 0, 0, 0), t120.xyzw' + $newline +
    'mul r24.xy, r24.xxxx, cb0[3].zwzz' + $newline +
    'add r12.xy, r12.xyxx, -r24.xyxx')
$modified = $modified.Replace($secondAnchor, 'mad r12.x, r24.x, l(2.000000), r12.x' + $newline + $secondAnchor)
$modified = $modified.Replace($thirdAnchor, 'mad r12.xy, r24.xyxx, l(-2.000000, 2.000000, 0.000000, 0.000000), r12.xyxx' + $newline + $thirdAnchor)
$modified = $modified.Replace($fourthAnchor, 'mad r12.x, r24.x, l(2.000000), r12.x' + $newline + $fourthAnchor)
$modified = $headerText + $newline + '//Frustum Fix' + $newline + $modified

$runtimeAssembly = Join-Path $payloadShaders '62b33a2d1e505241-cs.txt'
$authoredAssembly = Join-Path $validation '62b-native-shadow-filter-test.asm'
[IO.File]::WriteAllText($runtimeAssembly, $modified, $utf8)
[IO.File]::WriteAllText($authoredAssembly, $modified, $utf8)
Invoke-Assembler @('-a','--copy-reflection',$original,$authoredAssembly) (Join-Path $validation 'assemble.log')

$candidateBinary = Join-Path $validation '62b-native-shadow-filter-test.shdr'
if (-not (Test-Path -LiteralPath $candidateBinary -PathType Leaf)) { throw 'Assembler produced no native-filter test shader.' }
$verifyBinary = Join-Path $validation '62b-native-shadow-filter-test-verified.bin'
Copy-Item -LiteralPath $candidateBinary -Destination $verifyBinary
Invoke-Assembler @('-d','-V',$verifyBinary) (Join-Path $validation 'verify.log')
$verifiedAssembly = Join-Path $validation '62b-native-shadow-filter-test-verified.asm'
$verified = [IO.File]::ReadAllText($verifiedAssembly)
foreach ($required in @(
    'ld_indexable(texture1d)(float,float,float,float) r24.x, l(28, 0, 0, 0), t120.xyzw',
    'mul r24.xy, r24.xxxx, cb0[3].zwzz',
    'add r12.xy, r12.xyxx, -r24.xyxx',
    'mad r12.x, r24.x, l(2.000000), r12.x',
    'mad r12.xy, r24.xyxx, l(-2.000000, 2.000000, 0.000000, 0.000000), r12.xyxx'
)) {
    if ($verified -notmatch [regex]::Escape($required)) { throw "Verified shader is missing: $required" }
}
if ([regex]::Matches($verified,'gather4_aoffimmi_indexable').Count -ne [regex]::Matches($source,'gather4_aoffimmi_indexable').Count) {
    throw 'Native gather instruction count changed unexpectedly.'
}

$ini = @'
; Native 62b shadow-map filter ownership test. Page Down remains the master; Page Up is the test cycle.
[Constants]
global $ue4fx_master_injected_v1 = 1
global $ue4fx_native_shadow_filter_extra_v1 = 0
global $ue4fx_contact_edge_width_v2 = 0.06
global $ue4fx_contact_edge_cutoff_v2 = 0

[KeyUE4FXNativeShadowFilterPageUp]
key = no_modifiers VK_PRIOR
type = cycle
smart = true
; Native/default, then approximately 2x, 3x, and 4x gather-corner spacing.
$ue4fx_native_shadow_filter_extra_v1 = 0, 1, 2, 3

[KeyUE4FXMasterPageDown]
key = no_modifiers VK_NEXT
type = cycle
smart = true
$ue4fx_master_injected_v1 = 0, 1

[ShaderOverrideUE4FXContactc30cdc8365df9840]
hash = c30cdc8365df9840
x29 = $ue4fx_contact_edge_width_v2
y29 = $ue4fx_contact_edge_cutoff_v2
x31 = $ue4fx_master_injected_v1
y31 = -1
z31 = 1
w31 = 100

[ShaderOverrideUE4FXContact62b33a2d1e505241]
hash = 62b33a2d1e505241
x28 = $ue4fx_native_shadow_filter_extra_v1
x29 = $ue4fx_contact_edge_width_v2
y29 = $ue4fx_contact_edge_cutoff_v2
x31 = $ue4fx_master_injected_v1
y31 = -1
z31 = 1
w31 = 100

[ShaderOverrideUE4FXContact5a9fbefe0ab6f815]
hash = 5a9fbefe0ab6f815
x29 = $ue4fx_contact_edge_width_v2
y29 = $ue4fx_contact_edge_cutoff_v2
x31 = $ue4fx_master_injected_v1
y31 = -1
z31 = 1
w31 = 100

[ShaderOverrideUE4FXContact0e97888f9a8767da]
hash = 0e97888f9a8767da
x29 = $ue4fx_contact_edge_width_v2
y29 = $ue4fx_contact_edge_cutoff_v2
x31 = $ue4fx_master_injected_v1
y31 = -1
z31 = 1
w31 = 100

[ShaderOverrideUE4FXContact08bb8764f1840179]
hash = 08bb8764f1840179
x29 = $ue4fx_contact_edge_width_v2
y29 = $ue4fx_contact_edge_cutoff_v2
x31 = $ue4fx_master_injected_v1
y31 = -1
z31 = 1
w31 = 100
'@
$iniPath = Join-Path $payloadMods 'ContactShadows.ini'
[IO.File]::WriteAllText($iniPath, $ini.TrimStart() + $newline, $utf8)

$manifest = [ordered]@{
    schemaVersion = 1
    testId = 'ff7r-native-shadow-62b-filter-v1'
    status = 'offline-assembled-awaiting-focused-runtime-test'
    runtimeEligible = $false
    installed = $false
    target = 'sharp cone cast shadow on ground'
    baselineSha256 = $expectedBaselineSha256
    originalHeaderSha256 = $expectedHeaderSha256
    candidateSha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $candidateBinary).Hash
    controls = [ordered]@{master='Page Down';experiment='Page Up';states=@('native','2x-corner-spacing','3x-corner-spacing','4x-corner-spacing')}
    scope = '62b tiled local-light native t9/s3 shadow-map PCF block only; retained contact/frustum code is unchanged.'
    limitation = 'Sparse gather-corner widening is an ownership/width test, not the final dense soft-shadow kernel.'
}
[IO.File]::WriteAllText((Join-Path $output 'test-manifest.json'), ($manifest | ConvertTo-Json -Depth 8) + $newline, $utf8)

[pscustomobject]@{
    Output = $output
    Shader = '62b33a2d1e505241-cs'
    CandidateSha256 = $manifest.candidateSha256
    States = 4
    RuntimeEligible = $false
    Installed = $false
}
