[CmdletBinding()]
param(
    [string]$DonorDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'reference\external\shader-injector-v2.2.1\maximum-quality\shader-injector-2-2-1-maximum-dood\ShaderInjector\ModifiedShaders'),
    [string]$CaptureManifest = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts\validation-captures\ff7r-contact-area-baseline-20260831\capture-manifest.json'),
    [string]$SemanticReport,
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts\analysis\rebirth-v2.2.1-remake-area-inventory.json')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$workspace = [IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot)).TrimEnd('\')

function Assert-NonEmptyString {
    param($Value, [string]$Context)
    if ($Value -isnot [string] -or [string]::IsNullOrWhiteSpace($Value)) {
        throw "$Context must be a non-empty string."
    }
}

function Get-RequiredProperty {
    param([object]$Object, [string]$Name, [string]$Context)
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) { throw "$Context is missing '$Name'." }
    $property.Value
}

function Resolve-ExistingPath {
    param([string]$Path, [string]$Context, [switch]$Leaf)
    if ($Leaf) {
        if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
            throw "$Context does not exist: $Path"
        }
    } elseif (-not (Test-Path -LiteralPath $Path -PathType Container)) {
        throw "$Context does not exist: $Path"
    }
    (Resolve-Path -LiteralPath $Path).Path
}

$donorRoot = Resolve-ExistingPath $DonorDirectory 'Donor directory'
$captureManifestPath = Resolve-ExistingPath $CaptureManifest 'Capture manifest' -Leaf
$captureRoot = Split-Path -Parent $captureManifestPath

function Get-WorkspaceRelativePath {
    param([string]$Path)
    [IO.Path]::GetRelativePath($workspace,[IO.Path]::GetFullPath($Path)).Replace('\','/')
}

$capture = Get-Content -Raw -LiteralPath $captureManifestPath | ConvertFrom-Json
if ((Get-RequiredProperty $capture 'schemaVersion' 'Capture manifest') -ne 1) {
    throw "Unsupported capture manifest schema: $($capture.schemaVersion)"
}
$captureId = Get-RequiredProperty $capture 'captureId' 'Capture manifest'
Assert-NonEmptyString $captureId 'Capture manifest captureId'
$capturedShaders = @(Get-RequiredProperty $capture 'shaders' 'Capture manifest')
$declaredCaptureCount = [int](Get-RequiredProperty $capture 'capturedShaderCount' 'Capture manifest')
if ($capturedShaders.Count -ne $declaredCaptureCount) {
    throw "Capture count mismatch: manifest declares $declaredCaptureCount but contains $($capturedShaders.Count)."
}

$captureKeys = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
$captureStageCounts = [ordered]@{ vs = 0; ps = 0; cs = 0; gs = 0; hs = 0; ds = 0 }
$captureRows = foreach ($shader in $capturedShaders) {
    $shaderId = [string](Get-RequiredProperty $shader 'shader' 'Capture shader')
    if ($shaderId -notmatch '^(?<hash>[0-9a-fA-F]{16})-(?<stage>vs|ps|cs|gs|hs|ds)$') {
        throw "Invalid captured shader identifier: $shaderId"
    }
    if (-not $captureKeys.Add($shaderId)) {
        throw "Duplicate captured shader identifier: $shaderId"
    }
    $shaderHash = $Matches.hash.ToLowerInvariant()
    $stage = $Matches.stage.ToLowerInvariant()
    $captureStageCounts[$stage]++

    $binaryRelative = [string](Get-RequiredProperty $shader 'binary' "Capture shader $shaderId")
    $assemblyRelative = [string](Get-RequiredProperty $shader 'assembly' "Capture shader $shaderId")
    $binaryPath = Join-Path $captureRoot $binaryRelative
    $assemblyPath = Join-Path $captureRoot $assemblyRelative
    [void](Resolve-ExistingPath $binaryPath "Binary for $shaderId" -Leaf)
    [void](Resolve-ExistingPath $assemblyPath "Assembly for $shaderId" -Leaf)
    $assemblyText = Get-Content -Raw -LiteralPath $assemblyPath
    if ($assemblyText -notmatch 'Generated by Microsoft \(R\) D3D Shader Disassembler') {
        throw "Assembly for $shaderId is missing its original disassembler header."
    }
    if ($assemblyText -notmatch "(?m)^$($stage)_5_0\s*$") {
        throw "Assembly for $shaderId is missing its expected $($stage)_5_0 model declaration."
    }

    [pscustomobject][ordered]@{
        shader = $shaderId
        hash = $shaderHash
        stage = $stage
        binary = $binaryRelative.Replace('\', '/')
        assembly = $assemblyRelative.Replace('\', '/')
        originalDisassemblerHeaderRetained = $true
    }
}

$fingerprintFiles = @(Get-ChildItem -LiteralPath $donorRoot -Recurse -File -Filter '*_Fingerprint.json' |
    Sort-Object FullName)
if (-not $fingerprintFiles.Count) {
    throw "No donor fingerprint manifests were found below $donorRoot."
}

$donorRows = foreach ($file in $fingerprintFiles) {
    $manifest = Get-Content -Raw -LiteralPath $file.FullName | ConvertFrom-Json
    $context = "Donor manifest $($file.FullName)"
    if ((Get-RequiredProperty $manifest 'schemaVersion' $context) -ne 2) {
        throw "$context uses an unsupported schema."
    }
    if ((Get-RequiredProperty $manifest 'format' $context) -ne 'ShaderInjector.ModifiedShader') {
        throw "$context has an unsupported format."
    }

    $name = [string](Get-RequiredProperty $manifest 'name' $context)
    if ($name -notmatch '^GameVersion(?<version>[0-9_]+)_(?<family>[A-Za-z0-9]+)$') {
        throw "$context has an unsupported package name: $name"
    }
    $versionGroup = $Matches.version
    $family = $Matches.family
    $profile = [string](Get-RequiredProperty $manifest 'shaderProfile' $context)
    if ($profile -notmatch '^(?<stage>ps|cs)_6_6$') {
        throw "$context has an unexpected profile: $profile"
    }
    $stage = $Matches.stage

    $sourceFile = [string](Get-RequiredProperty $manifest 'sourceFile' $context)
    $blobFile = [string](Get-RequiredProperty $manifest 'compiledBlobFile' $context)
    $sourcePath = Resolve-ExistingPath (Join-Path $file.DirectoryName $sourceFile) "$context source" -Leaf
    [void](Resolve-ExistingPath (Join-Path $file.DirectoryName $blobFile) "$context blob" -Leaf)
    $sourceText = Get-Content -Raw -LiteralPath $sourcePath
    $includes = @([regex]::Matches($sourceText, '(?m)^\s*#include\s+"(?<path>[^"]+)"') |
        ForEach-Object { $_.Groups['path'].Value })
    $defines = @([regex]::Matches($sourceText, '(?m)^\s*#define\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)') |
        ForEach-Object { $_.Groups['name'].Value })

    $targets = @(Get-RequiredProperty $manifest 'targets' $context)
    if (-not $targets.Count) { throw "$context contains no targets." }
    $targetRows = foreach ($target in $targets) {
        $analysis = Get-RequiredProperty $target 'shaderAnalysis' "$context target"
        $hashes = @(Get-RequiredProperty $target 'knownShaderBytecodeHashes' "$context target")
        if (-not $hashes.Count) { throw "$context target contains no known hashes." }
        foreach ($hash in $hashes) {
            if ([string]$hash -notmatch '^[0-9A-Fa-f]{16}$') {
                throw "$context target contains an invalid hash: $hash"
            }
        }
        [pscustomobject][ordered]@{
            name = [string](Get-RequiredProperty $target 'name' "$context target")
            knownHashes = @($hashes | ForEach-Object { ([string]$_).ToUpperInvariant() })
            originalBytecodeLength = [int64](Get-RequiredProperty $target 'originalShaderBytecodeLength' "$context target")
            portableReflectionIdentityHash = [string](Get-RequiredProperty $analysis 'portableReflectionIdentityHash' "$context target analysis")
            crossVersionIdentityHash = [string](Get-RequiredProperty $analysis 'crossVersionIdentityHash' "$context target analysis")
            semanticInstructionSetHash = [string](Get-RequiredProperty $analysis 'semanticInstructionSetHash' "$context target analysis")
            normalizedInstructionCount = [int](Get-RequiredProperty $analysis 'normalizedInstructionCount' "$context target analysis")
            uniqueNormalizedInstructionCount = [int](Get-RequiredProperty $analysis 'uniqueNormalizedInstructionCount' "$context target analysis")
        }
    }

    [pscustomobject][ordered]@{
        name = $name
        family = $family
        versionGroup = $versionGroup
        stage = $stage
        profile = $profile
        entryPoint = [string](Get-RequiredProperty $manifest 'shaderEntryPoint' $context)
        sourceFile = $sourceFile
        compiledBlobFile = $blobFile
        includes = $includes
        defines = $defines
        targets = $targetRows
    }
}

$duplicatePackages = @($donorRows | Group-Object name | Where-Object Count -gt 1)
if ($duplicatePackages.Count) {
    throw "Duplicate donor package names: $($duplicatePackages.Name -join ', ')"
}

if ([string]::IsNullOrWhiteSpace($SemanticReport)) {
    $semanticRelative = $capture.PSObject.Properties['semanticReport']
    if ($null -ne $semanticRelative -and -not [string]::IsNullOrWhiteSpace([string]$semanticRelative.Value)) {
        $SemanticReport = Join-Path $captureRoot ([string]$semanticRelative.Value)
    }
}

$semanticRows = @()
if (-not [string]::IsNullOrWhiteSpace($SemanticReport)) {
    $semanticPath = Resolve-ExistingPath $SemanticReport 'Semantic report' -Leaf
    $semantic = Get-Content -Raw -LiteralPath $semanticPath | ConvertFrom-Json
    $semanticRows = @($semantic.matches | ForEach-Object {
        $hash = ([string]$_.hash).ToLowerInvariant()
        $stage = ([string]$_.stage).ToLowerInvariant()
        $key = "$hash-$stage"
        if (-not $captureKeys.Contains($key)) {
            throw "Semantic match $key is not present in capture $captureId."
        }
        [pscustomobject][ordered]@{
            descriptor = [string]$_.descriptor
            family = [string]$_.family
            displayName = [string]$_.displayName
            hash = $hash
            stage = $stage
            shaderModel = [string]$_.shaderModel
            semanticChecksPassed = [int]$_.semanticChecksPassed
        }
    })
}

$familyRows = @($donorRows | Group-Object family | Sort-Object Name | ForEach-Object {
    $packages = @($_.Group | Sort-Object versionGroup)
    $stages = @($packages.stage | Sort-Object -Unique)
    if ($stages.Count -ne 1) {
        throw "Donor family '$($_.Name)' spans multiple stages: $($stages -join ', ')"
    }
    [pscustomobject][ordered]@{
        family = $_.Name
        stage = $stages[0]
        versionGroups = @($packages.versionGroup)
        packageCount = $packages.Count
        targetCount = @($packages | ForEach-Object { @($_.targets) }).Count
        sharedIncludes = @($packages | ForEach-Object { @($_.includes) } | Sort-Object -Unique)
        variantDefines = @($packages | ForEach-Object { @($_.defines) } | Sort-Object -Unique)
        packages = $packages
    }
})

$donorStageCounts = [ordered]@{}
foreach ($stageGroup in @($familyRows | Group-Object stage | Sort-Object Name)) {
    $donorStageCounts[$stageGroup.Name] = $stageGroup.Count
}

$report = [pscustomobject][ordered]@{
    schemaVersion = 1
    reportType = 'RebirthDonorRemakeCaptureInventory'
    donor = [pscustomobject][ordered]@{
        directory = Get-WorkspaceRelativePath $donorRoot
        packageCount = $donorRows.Count
        familyCount = $familyRows.Count
        versionGroups = @($donorRows.versionGroup | Sort-Object -Unique)
        stageFamilyCounts = [pscustomobject]$donorStageCounts
        targetCount = @($donorRows.targets).Count
        families = $familyRows
    }
    capture = [pscustomobject][ordered]@{
        captureId = $captureId
        manifest = Get-WorkspaceRelativePath $captureManifestPath
        shaderCount = $captureRows.Count
        stageShaderCounts = [pscustomobject]$captureStageCounts
        originalDisassemblerHeaderCount = @($captureRows | Where-Object originalDisassemblerHeaderRetained).Count
        shaders = @($captureRows | Sort-Object stage, hash)
        semanticMatchCount = $semanticRows.Count
        semanticMatches = @($semanticRows | Sort-Object family, descriptor, hash)
    }
}

$outputDirectory = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
    [void](New-Item -ItemType Directory -Force -Path $outputDirectory)
}
$report | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $OutputPath -Encoding utf8

[pscustomobject]@{
    OutputPath = (Resolve-Path -LiteralPath $OutputPath).Path
    DonorPackages = $donorRows.Count
    DonorFamilies = $familyRows.Count
    DonorStageFamilies = ($donorStageCounts.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join ', '
    CaptureShaders = $captureRows.Count
    CaptureStages = ($captureStageCounts.GetEnumerator() | Where-Object Value -gt 0 |
        ForEach-Object { "$($_.Key)=$($_.Value)" }) -join ', '
    SemanticMatches = $semanticRows.Count
}
