[CmdletBinding()]
param(
    [string]$CaptureManifestPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts\validation-captures\ff7r-contact-area-baseline-20260831\capture-manifest.json'),
    [string]$ClassificationManifestPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'src\Adapters\FF7RemakeIntergrade\verified-shader-classifications.json'),
    [string]$AssemblerPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts\shader-assembler-build\bin\cmd_Decompiler.exe'),
    [Parameter(Mandatory)][string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path.TrimEnd('\')
$artifactsRoot = Join-Path $repo 'artifacts'
$output = [IO.Path]::GetFullPath($OutputDirectory).TrimEnd('\')
if (-not $output.StartsWith($artifactsRoot + '\', [StringComparison]::OrdinalIgnoreCase)) {
    throw 'Diagnostic output must stay below workspace artifacts.'
}
if (Test-Path -LiteralPath $output) {
    throw 'Diagnostic output already exists; preserve prior evidence.'
}

$captureManifestFull = (Resolve-Path -LiteralPath $CaptureManifestPath).Path
$classificationManifestFull = (Resolve-Path -LiteralPath $ClassificationManifestPath).Path
$assembler = (Resolve-Path -LiteralPath $AssemblerPath).Path
$capture = Get-Content -Raw -LiteralPath $captureManifestFull | ConvertFrom-Json
$classifications = Get-Content -Raw -LiteralPath $classificationManifestFull | ConvertFrom-Json

if ([string]$capture.captureId -ne 'ff7r-contact-area-baseline-20260831') {
    throw 'Unexpected capture identity.'
}
if ([string]$classifications.captureId -ne [string]$capture.captureId) {
    throw 'Classification and capture identities disagree.'
}

$shaderId = 'b9e2305a994308f2-cs'
$shaderHash = 'b9e2305a994308f2'
$captureRows = @($capture.shaders | Where-Object shader -eq $shaderId)
if ($captureRows.Count -ne 1) {
    throw 'Expected exactly one captured capsule producer.'
}
$family = @($classifications.families | Where-Object familyId -eq 'tiled-capsule-occlusion-producer')
if ($family.Count -ne 1 -or [string]$family[0].stage -ne 'cs' -or [string]$family[0].insertionEligibility -ne 'excluded-upstream-producer') {
    throw 'Capsule producer classification is absent or unsafe.'
}
$familyHashes = @($family[0].hashes | ForEach-Object { [string]$_.hash })
if ($familyHashes.Count -ne 1 -or $familyHashes[0] -ne $shaderHash) {
    throw 'Capsule producer family identity changed.'
}

$captureRoot = Split-Path -Parent $captureManifestFull
$originalBinary = (Resolve-Path -LiteralPath (Join-Path $captureRoot ([string]$captureRows[0].binary))).Path
$retainedAssembly = (Resolve-Path -LiteralPath (Join-Path $captureRoot ([string]$captureRows[0].assembly))).Path
$originalSha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $originalBinary).Hash
if ($originalSha256 -ne [string]$captureRows[0].sourceSha256) {
    throw 'Captured capsule binary fingerprint changed.'
}
$retainedText = Get-Content -Raw -LiteralPath $retainedAssembly
if ($retainedText -notmatch 'Generated by Microsoft \(R\) D3D Shader Disassembler' -or $retainedText -notmatch '(?m)^cs_5_0\r?$') {
    throw 'Original capsule assembly header or shader model is missing.'
}

function Invoke-Assembler([string[]]$Arguments, [string]$LogPath) {
    $messages = & $assembler @Arguments 2>&1
    $exitCode = $LASTEXITCODE
    [IO.File]::WriteAllText($LogPath, ($messages | Out-String), [Text.UTF8Encoding]::new($false))
    if ($exitCode -ne 0) {
        throw "Assembler failed; see $LogPath"
    }
}

[IO.Directory]::CreateDirectory($output) | Out-Null
$validation = Join-Path $output 'validation'
$payloadMods = Join-Path $output 'payload\Mods'
$payloadShaderFixes = Join-Path $output 'payload\ShaderFixes'
foreach ($directory in @($validation, $payloadMods, $payloadShaderFixes)) {
    [IO.Directory]::CreateDirectory($directory) | Out-Null
}

$originalCopy = Join-Path $validation 'original.bin'
Copy-Item -LiteralPath $originalBinary -Destination $originalCopy
Invoke-Assembler @('-d', '-V', $originalCopy) (Join-Path $validation 'original-disassembly.log')
$originalAsm = Join-Path $validation 'original.asm'
if (-not (Test-Path -LiteralPath $originalAsm -PathType Leaf)) {
    throw 'Assembler produced no original assembly.'
}
Invoke-Assembler @('-a', '--copy-reflection', $originalCopy, $originalAsm) (Join-Path $validation 'neutral-roundtrip.log')
$neutralBinary = Join-Path $validation 'original.shdr'
if ((Get-FileHash -Algorithm SHA256 -LiteralPath $neutralBinary).Hash -ne $originalSha256) {
    throw 'Neutral capsule round trip is not byte-identical.'
}

$source = [IO.File]::ReadAllText($originalAsm).Replace("`r`n", "`n")
if ($source -match '\bt120\b') {
    throw 'Native capsule producer already consumes t120.'
}
if ([regex]::Matches($source, '(?m)^dcl_temps 15$').Count -ne 1) {
    throw 'Expected the proven 15-temporary capsule layout.'
}
$lastR14 = [regex]::Matches($source, '(?m)^.*\br14(?:\.[xyzw]+)?\b.*$') | Select-Object -Last 1
$outputStoreIndex = $source.IndexOf('store_uav_typed u0.xyzw, vThreadID.xyyy, r3.xyzw', [StringComparison]::Ordinal)
if ($null -eq $lastR14 -or $lastR14.Index -ge $outputStoreIndex) {
    throw 'r14 is not proven dead at the output patch point.'
}

$declarationAnchor = 'dcl_resource_buffer (float,float,float,float) t3'
$storeAnchor = 'store_uav_typed u0.xyzw, vThreadID.xyyy, r3.xyzw'
if ([regex]::Matches($source, [regex]::Escape($declarationAnchor)).Count -ne 1 -or
    [regex]::Matches($source, [regex]::Escape($storeAnchor)).Count -ne 1 -or
    [regex]::Matches($source, 'store_uav_typed u1\.xyzw, r0\.wwww, r0\.xxxx').Count -ne 1) {
    throw 'Capsule output or candidate-list anchors are not unique.'
}

$controlDeclaration = 'dcl_resource_texture1d (float,float,float,float) t120'
$injected = @(
    'ld_indexable(texture1d)(float,float,float,float) r14.xy, l(28, 0, 0, 0), t120.xyzw',
    'mul r14.x, r14.x, r14.y',
    'if_nz r14.x',
    '  mov r3.xy, l(1.000000,1.000000,0,0)',
    'endif'
)
$modified = $source.Replace($declarationAnchor, $declarationAnchor + "`n" + $controlDeclaration)
$modified = $modified.Replace($storeAnchor, ($injected -join "`n") + "`n" + $storeAnchor)

$authoredAsm = Join-Path $validation 'capsule-neutral-diagnostic.asm'
[IO.File]::WriteAllText($authoredAsm, $modified, [Text.UTF8Encoding]::new($false))
Invoke-Assembler @('-a', '--copy-reflection', $originalCopy, $authoredAsm) (Join-Path $validation 'candidate-assembly.log')
$candidateBinary = Join-Path $validation 'capsule-neutral-diagnostic.shdr'
if (-not (Test-Path -LiteralPath $candidateBinary -PathType Leaf)) {
    throw 'Assembler produced no capsule diagnostic binary.'
}
$verifyBinary = Join-Path $validation 'capsule-neutral-verified.bin'
Copy-Item -LiteralPath $candidateBinary -Destination $verifyBinary
Invoke-Assembler @('-d', '-V', $verifyBinary) (Join-Path $validation 'candidate-validation.log')
$verifiedAsm = Join-Path $validation 'capsule-neutral-verified.asm'
$verified = Get-Content -Raw -LiteralPath $verifiedAsm
foreach ($required in @(
    'dcl_resource_texture1d (float,float,float,float) t120',
    'ld_indexable(texture1d)(float,float,float,float) r14.xy, l(28, 0, 0, 0), t120.xyzw',
    'mul r14.x, r14.x, r14.y',
    'mov r3.xy, l(1.000000,1.000000,0,0)',
    'store_uav_typed u1.xyzw, r0.wwww, r0.xxxx',
    'store_uav_typed u0.xyzw, vThreadID.xyyy, r3.xyzw'
)) {
    if ($verified -notmatch [regex]::Escape($required)) {
        throw "Verified capsule diagnostic is missing: $required"
    }
}

$runtimeAssembly = Join-Path $payloadShaderFixes ($shaderId + '.txt')
[IO.File]::WriteAllText($runtimeAssembly, $modified, [Text.UTF8Encoding]::new($false))
$ini = @'
; Focused diagnostic only. Not release-ready and not automatically installed.
; Page Down gates every injected instruction. Page Up gates this experiment.
; Page Up ON neutralizes only b9e capsule visibility u0.xy to 1.0.
; Native u0.zw, candidate-list u1, depth work, and all original code remain.
[Constants]
global $ue4fx_master_injected_v1 = 1
global $ue4fx_capsule_ownership_v1 = 0

[KeyUE4FXMasterPageDown]
key = no_modifiers VK_NEXT
type = cycle
smart = true
$ue4fx_master_injected_v1 = 0, 1

[KeyUE4FXCapsuleOwnershipPageUp]
key = no_modifiers VK_PRIOR
type = cycle
smart = true
$ue4fx_capsule_ownership_v1 = 0, 1

[ShaderOverrideUE4FXCapsuleOwnershipB9E]
hash = b9e2305a994308f2
x28 = $ue4fx_master_injected_v1
y28 = $ue4fx_capsule_ownership_v1
'@
$iniPath = Join-Path $payloadMods 'CapsuleOcclusionOwnership.ini'
[IO.File]::WriteAllText($iniPath, $ini.TrimStart() + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))

$manifest = [ordered]@{
    schemaVersion = 1
    diagnosticId = 'ff7r-capsule-occlusion-ownership-v1'
    shader = $shaderId
    family = 'tiled-capsule-occlusion-producer'
    captureId = [string]$capture.captureId
    status = 'offline-assembled-awaiting-focused-runtime-test'
    runtimeEligible = $false
    installed = $false
    originalSha256 = $originalSha256
    neutralRoundTripIdentical = $true
    control = [ordered]@{
        iniRow = 28
        masterComponent = 'x'
        experimentComponent = 'y'
        masterKey = 'Page Down'
        experimentKey = 'Page Up'
        experimentDefault = 'off'
    }
    change = [ordered]@{
        condition = 'master * experiment is nonzero'
        modifiedOutput = 'u0.xy capsule visibility forced to neutral 1.0'
        preservedOutputs = @('u0.zw depth/validity payload', 'u1 capsule candidate/list data')
        preservedExecution = 'all original depth reduction, culling, capsule evaluation, and output stores'
    }
    interpretation = [ordered]@{
        characterOnly = 'not assumed'
        positiveResult = 'changed pixels identify visible ownership of the native capsule-occlusion producer in the test scene'
        negativeResult = 'no visible difference means the scene lacks visible capsule contribution or the pass is inactive; it does not disprove the structural classification'
    }
    files = @(
        [ordered]@{ path = 'payload/Mods/CapsuleOcclusionOwnership.ini'; sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $iniPath).Hash },
        [ordered]@{ path = 'payload/ShaderFixes/b9e2305a994308f2-cs.txt'; sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $runtimeAssembly).Hash },
        [ordered]@{ path = 'validation/capsule-neutral-diagnostic.shdr'; sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $candidateBinary).Hash }
    )
}
$manifestPath = Join-Path $output 'diagnostic-manifest.json'
[IO.File]::WriteAllText($manifestPath, ($manifest | ConvertTo-Json -Depth 10) + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))

[pscustomobject]@{
    Output = $output
    Shader = $shaderId
    NeutralRoundTripIdentical = $true
    RuntimeEligible = $false
    Installed = $false
    ExperimentDefault = 'off'
}
