[CmdletBinding()]
param(
    [string]$RuntimeRoot = 'C:\Games\Final.Fantasy.VII.Remake.Intergrade-InsaneRamZes\End\Binaries\Win64',
    [string]$OriginalDirectory,
    [string]$OutputDirectory,
    [switch]$Install
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path.TrimEnd('\')
$runtime = (Resolve-Path -LiteralPath $RuntimeRoot).Path.TrimEnd('\')
if ([string]::IsNullOrWhiteSpace($OriginalDirectory)) {
    $OriginalDirectory = Join-Path $repo 'working-code\Contact shadows - Rebirth Mod - Code worked\original-remake'
}
$originalRoot = (Resolve-Path -LiteralPath $OriginalDirectory).Path.TrimEnd('\')
$stamp = [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss-fff')
if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $repo "artifacts\shader-header-restorations\$stamp"
}
$output = [IO.Path]::GetFullPath($OutputDirectory).TrimEnd('\')
$allowed = [IO.Path]::GetFullPath((Join-Path $repo 'artifacts\shader-header-restorations')).TrimEnd('\')
if (-not $output.StartsWith($allowed + '\', [StringComparison]::OrdinalIgnoreCase)) { throw 'Output must remain below artifacts/shader-header-restorations.' }
if (Test-Path -LiteralPath $output) { throw 'Output already exists; preserve prior evidence.' }

$names = @(
    '08bb8764f1840179-cs',
    '0e97888f9a8767da-cs',
    '5a9fbefe0ab6f815-cs',
    '62b33a2d1e505241-cs',
    'c30cdc8365df9840-cs'
)
$utf8 = [Text.UTF8Encoding]::new($false)
$stage = Join-Path $output 'ShaderFixes'
[IO.Directory]::CreateDirectory($stage) | Out-Null

function Get-InstructionText([string[]]$Lines) {
    return (($Lines | ForEach-Object { $_.Trim() } | Where-Object { $_ -and -not $_.StartsWith('//') }) -join "`n")
}

$records = @()
foreach ($name in $names) {
    $originalPath = Join-Path $originalRoot ($name + '.asm')
    $livePath = Join-Path $runtime ('ShaderFixes\' + $name + '.txt')
    if (-not (Test-Path -LiteralPath $originalPath -PathType Leaf)) { throw "Missing saved original: $originalPath" }
    if (-not (Test-Path -LiteralPath $livePath -PathType Leaf)) { throw "Missing live replacement: $livePath" }

    $originalLines = @(Get-Content -LiteralPath $originalPath)
    $originalProfile = [array]::IndexOf($originalLines, 'cs_5_0')
    if ($originalProfile -lt 1) { throw "Saved original lacks a comment header: $originalPath" }
    $header = @($originalLines[0..($originalProfile - 1)])
    if (@($header | Where-Object { $_.Trim() -and -not $_.TrimStart().StartsWith('//') }).Count) { throw "Saved header contains instructions: $originalPath" }
    $headerText = $header -join "`n"
    if ($headerText -notmatch 'Generated by Microsoft \(R\) D3D Shader Disassembler' -or
        $headerText -notmatch 'using 3Dmigoto' -or $headerText -notmatch 'Input signature:' -or
        $headerText -notmatch 'Output signature:') { throw "Saved original header is incomplete: $originalPath" }

    $liveLines = @(Get-Content -LiteralPath $livePath)
    $liveProfile = [array]::IndexOf($liveLines, 'cs_5_0')
    if ($liveProfile -lt 0) { throw "Live replacement lacks cs_5_0: $livePath" }
    $body = @($liveLines[$liveProfile..($liveLines.Count - 1)])
    $beforeInstructions = Get-InstructionText $liveLines
    $afterLines = @($header + $body)
    $afterInstructions = Get-InstructionText $afterLines
    if ($beforeInstructions -cne $afterInstructions) { throw "Header restoration changed shader instructions: $name" }

    $stagedPath = Join-Path $stage ($name + '.txt')
    [IO.File]::WriteAllText($stagedPath, (($afterLines -join "`n") + "`n"), $utf8)
    $roundTrip = @(Get-Content -LiteralPath $stagedPath)
    if ((Get-InstructionText $roundTrip) -cne $beforeInstructions) { throw "Staged instruction round trip changed: $name" }

    $records += [ordered]@{
        shader = $name
        originalHeaderSource = $originalPath
        headerLines = $header.Count
        liveBeforeSha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $livePath).Hash
        stagedSha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $stagedPath).Hash
        instructionSha256 = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($utf8.GetBytes($beforeInstructions)))
    }
}

$rollback = $null
if ($Install) {
    $rollback = Join-Path $repo "artifacts\live-rollbacks\shader-header-restoration-$stamp"
    if (Test-Path -LiteralPath $rollback) { throw 'Rollback directory already exists.' }
    $rollbackFixes = Join-Path $rollback 'ShaderFixes'
    [IO.Directory]::CreateDirectory($rollbackFixes) | Out-Null
    foreach ($name in $names) {
        $livePath = Join-Path $runtime ('ShaderFixes\' + $name + '.txt')
        Copy-Item -LiteralPath $livePath -Destination (Join-Path $rollbackFixes ($name + '.txt'))
        Copy-Item -LiteralPath (Join-Path $stage ($name + '.txt')) -Destination $livePath -Force
    }
}

$manifest = [ordered]@{
    schemaVersion = 1
    generatedAtUtc = [DateTime]::UtcNow.ToString('o')
    result = if ($Install) { 'installed' } else { 'staged' }
    change = 'Restored authoritative Microsoft/3Dmigoto signature comments only; normalized shader instructions are identical.'
    runtimeRoot = $runtime
    originalDirectory = $originalRoot
    records = $records
    installed = [bool]$Install
    rollbackDirectory = $rollback
    reloadRequired = [bool]$Install
}
$manifestPath = Join-Path $output 'manifest.json'
[IO.File]::WriteAllText($manifestPath, (($manifest | ConvertTo-Json -Depth 8) + "`n"), $utf8)
[pscustomobject]@{
    Result = $manifest.result
    Shaders = $records.Count
    InstructionsChanged = $false
    Rollback = $rollback
    Manifest = $manifestPath
    Sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $manifestPath).Hash
}
