[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path.TrimEnd('\')
$fixtureRoot = Join-Path $repoRoot 'artifacts\ue4-validation-capture-import-fixture'
$shaderCache = Join-Path $fixtureRoot 'ShaderCache'
$output = Join-Path $repoRoot 'artifacts\validation-captures\test-fixture'
if (Test-Path -LiteralPath $fixtureRoot) { Remove-Item -LiteralPath $fixtureRoot -Recurse -Force }
[IO.Directory]::CreateDirectory($shaderCache) | Out-Null
Copy-Item -LiteralPath (Join-Path $repoRoot 'artifacts\PostProcessSmoke_ps.cso') -Destination (Join-Path $shaderCache 'ABCDEFABCDEFABCD-ps.bin')
& (Join-Path $repoRoot 'tools\Import-UE4ValidationCapture.ps1') -CaptureDirectory $fixtureRoot -CaptureId 'test-fixture' -OutputDirectory $output -NearMatchLimitPerDescriptor 2 | Out-Null
$manifest = Get-Content -Raw -LiteralPath (Join-Path $output 'capture-manifest.json') | ConvertFrom-Json
if ([int]$manifest.capturedShaderCount -ne 1) { throw 'Importer did not record exactly one shader.' }
if ([string]$manifest.shaders[0].shader -ne 'abcdefabcdefabcd-ps' -or [string]$manifest.shaders[0].binary -ne 'dxbc/abcdefabcdefabcd-ps.bin') { throw 'Importer did not canonicalize an uppercase shader hash.' }
if ([bool]$manifest.redistributionAllowed) { throw 'Captured game artifacts must fail closed on redistribution.' }
$assembly = Join-Path $output ([string]$manifest.shaders[0].assembly -replace '/', '\')
if (-not (Test-Path -LiteralPath $assembly -PathType Leaf)) { throw 'Importer did not emit assembly.' }
$assemblyText = [IO.File]::ReadAllText($assembly)
if ($assemblyText -notmatch 'Generated by Microsoft' -or $assemblyText -notmatch '(?m)^ps_5_0?$') { throw 'Imported assembly is not FXC SM5 disassembly.' }
if (-not (Test-Path -LiteralPath (Join-Path $output 'semantic-matches.json') -PathType Leaf)) { throw 'Semantic report is missing.' }
Write-Output 'UE4 validation capture import-and-scan test passed.'
