[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

$workspace=Split-Path $PSScriptRoot -Parent
$catalogPath=Join-Path $workspace 'artifacts\analysis\ue4-dxbc-semantic-family-catalog.json'
$assemblyPath=Join-Path $workspace 'artifacts\validation-captures\ff7r-contact-area-baseline-20260831\assembly'
$matchPath=Join-Path $workspace 'artifacts\analysis\ff7r-contact-area-baseline-20260831-portable-family-matches.json'
$candidatePath=Join-Path $workspace 'artifacts\analysis\ff7r-contact-area-baseline-20260831-alias-candidates.json'

& (Join-Path $PSScriptRoot 'Test-UE4SemanticShaderFamilyCatalog.ps1')
& (Join-Path $PSScriptRoot 'Match-DxbcShaderFamilyCatalog.ps1') -ShaderDirectory $assemblyPath -CatalogPath $catalogPath -OutputPath $matchPath -ExcludeReplacementArtifacts
& (Join-Path $PSScriptRoot 'New-ShaderFamilyAliasCandidates.ps1') -CatalogPath $catalogPath -MatchReportPath $matchPath -OutputPath $candidatePath
$firstMatchHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $matchPath).Hash
$firstCandidateHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $candidatePath).Hash
& (Join-Path $PSScriptRoot 'Match-DxbcShaderFamilyCatalog.ps1') -ShaderDirectory $assemblyPath -CatalogPath $catalogPath -OutputPath $matchPath -ExcludeReplacementArtifacts
& (Join-Path $PSScriptRoot 'New-ShaderFamilyAliasCandidates.ps1') -CatalogPath $catalogPath -MatchReportPath $matchPath -OutputPath $candidatePath
if((Get-FileHash -Algorithm SHA256 -LiteralPath $matchPath).Hash-ne$firstMatchHash){throw 'Portable family match report is not byte-deterministic'}
if((Get-FileHash -Algorithm SHA256 -LiteralPath $candidatePath).Hash-ne$firstCandidateHash){throw 'Alias candidate artifact is not byte-deterministic'}

$report=Get-Content -Raw -LiteralPath $candidatePath|ConvertFrom-Json
if($report.schemaVersion-ne1-or$report.kind-ne'shader-family-alias-candidates'){throw 'Alias-candidate envelope regression'}
if($report.candidateCount-ne1-or$report.candidates.Count-ne1){throw 'Expected exactly one structurally discovered non-fast-path candidate'}
$candidate=$report.candidates[0]
if($candidate.familyId-ne'ue4-motion-blur-scene-color-resolve-ps-sm5'-or$candidate.stage-ne'ps'-or$candidate.shaderHash-ne'EDA405F2D455D5C7'){throw 'Unexpected learned-alias candidate'}
if($candidate.semanticChecksPassed-ne11-or$candidate.status-ne'review-required'-or$candidate.catalogMutation-ne$false-or$candidate.runtimeEligible-ne$false){throw 'Alias candidate did not remain review-only and fully evidenced'}
$assembly=Join-Path $assemblyPath 'eda405f2d455d5c7-ps.asm'
if(-not(Test-Path -LiteralPath $assembly -PathType Leaf)){throw 'Candidate original assembly is missing'}
$header=Get-Content -Raw -LiteralPath $assembly
if($header-notmatch'Generated by Microsoft \(R\) D3D Shader Disassembler'-or$header-notmatch'(?m)^ps_5_0\s*$'){throw 'Candidate original disassembler header or model declaration is missing'}
$known=@('AF6CD28A0108A18A','E2AA1C8CB39E0A55','B2BC6059F9A39C7F','A77B589DCE5822D6','C25D7F5229662B97','CBC771FF8A37A0B3','EF7FE8D9C4E9AD15')
if($candidate.shaderHash-in$known){throw 'Existing fast path was incorrectly emitted as a candidate'}

Write-Host 'PASS: regional scan deterministically emits only EDA405F2D455D5C7 as a header-backed, review-only learned-alias candidate and mutates no catalog.'
