[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$me3Root = Join-Path $projectRoot 'reference\external\helix-me3-new-shader-override'
$shaderRoot = Join-Path $me3Root 'ShaderOverride'
$dx11Script = Join-Path $projectRoot 'reference\external\Helix-BioShockInfinite-UE3-DX11\PSscript.lua'
$me3Readme = Join-Path $me3Root 'README.md'

foreach ($path in @($shaderRoot, $dx11Script, $me3Readme)) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Historical evidence is missing: $path" }
}

$expectedScriptSha256 = '0EE2F122339FAC65755284B661520C07B908718BF37ABF98CEC2C93F24783F69'
if ((Get-FileHash -Algorithm SHA256 -LiteralPath $dx11Script).Hash -ne $expectedScriptSha256) {
    throw 'Preserved BioShock Infinite DX11 transformer script changed.'
}
if ((Get-Content -LiteralPath $dx11Script).Count -ne 838) {
    throw 'Preserved BioShock Infinite DX11 transformer line count changed.'
}

$allFiles = @(Get-ChildItem -LiteralPath $me3Root -Recurse -File)
$pixelFiles = @($allFiles | Where-Object FullName -Like '*\ShaderOverride\PixelShaders\*.txt')
$vertexFiles = @($allFiles | Where-Object FullName -Like '*\ShaderOverride\VertexShaders\*.txt')
$rootShaderFiles = @($allFiles | Where-Object {
    $_.DirectoryName -eq $shaderRoot -and $_.Name -like '*.txt*'
})
$shaderFiles = @($pixelFiles + $vertexFiles + $rootShaderFiles)

if ($allFiles.Count -ne 760) { throw "ME3 reference file count changed: $($allFiles.Count)" }
if ($pixelFiles.Count -ne 637) { throw "ME3 pixel-shader count changed: $($pixelFiles.Count)" }
if ($vertexFiles.Count -ne 115) { throw "ME3 vertex-shader count changed: $($vertexFiles.Count)" }
if ($rootShaderFiles.Count -ne 6) { throw "ME3 root shader-variant count changed: $($rootShaderFiles.Count)" }
if ($shaderFiles.Count -ne 758) { throw "ME3 shader-text count changed: $($shaderFiles.Count)" }
if (@($allFiles | Where-Object Extension -eq '.dll').Count) {
    throw 'Unexpected wrapper DLL appeared in the ME3 shader-only reference.'
}

$records = @(foreach ($file in $shaderFiles) {
    $kind = if ($file.FullName -like '*\PixelShaders\*') {
        'ps'
    } elseif ($file.FullName -like '*\VertexShaders\*') {
        'vs'
    } else {
        'root'
    }
    [pscustomobject]@{
        Kind = $kind
        Text = Get-Content -Raw -LiteralPath $file.FullName
    }
})

function Count-Marker([string]$marker, [string]$kind = '') {
    @($records | Where-Object {
        (-not $kind -or $_.Kind -eq $kind) -and $_.Text.Contains($marker)
    }).Count
}

$expected = [ordered]@{
    'bReceiveDynamicShadows' = 622
    'LightAttenuationTexture' = 622
    'ShadowViewProjection' = 5
    'LightPositionAndInvRadius' = 22
    'ShadowDepthTexture' = 6
    'ScreenPositionScaleBias' = 639
    'ViewProjectionMatrix' = 733
    'dcl_2d s14' = 636
    'texldl r11, c24.z, s14' = 632
}
foreach ($entry in $expected.GetEnumerator()) {
    $actual = Count-Marker $entry.Key
    if ($actual -ne $entry.Value) {
        throw "ME3 marker '$($entry.Key)' changed: expected $($entry.Value), got $actual."
    }
}

if ((Count-Marker 'bReceiveDynamicShadows' 'ps') -ne 622) {
    throw 'ME3 dynamic-shadow receiver marker is no longer pixel-stage-only.'
}
if ((Count-Marker 'ShadowViewProjection' 'vs') -ne 5) {
    throw 'ME3 shadow projection marker is no longer vertex-stage-only.'
}
if ((Count-Marker 'LightPositionAndInvRadius' 'vs') -ne 22) {
    throw 'ME3 local-light position/radius marker is no longer vertex-stage-only.'
}

$psModelCount = @($records | Where-Object Text -Match '(?m)^\s*ps_3_0\s*$').Count
$vsModelCount = @($records | Where-Object Text -Match '(?m)^\s*vs_3_0\s*$').Count
$headerCount = @($records | Where-Object Text -Match 'Generated by Microsoft \(R\) HLSL Shader Compiler').Count
if ($psModelCount -ne 641 -or $vsModelCount -ne 117) {
    throw "ME3 shader-model counts changed: ps_3_0=$psModelCount, vs_3_0=$vsModelCount."
}
if ($headerCount -ne 758) { throw "ME3 retained compiler-header count changed: $headerCount" }

$readme = Get-Content -Raw -LiteralPath $me3Readme
$archiveSha256 = 'F9D05DE454699A1DD4FF43BCB7DD32B53A975F3D0A035FE2E56302411844F902'
if (-not $readme.Contains($archiveSha256)) { throw 'ME3 provenance README lost the source archive hash.' }

Write-Host 'PASS: Helix UE3 evidence is preserved: BioShock DX11 transformer plus 758 header-complete ME3 DX9 shader variants.'
