[CmdletBinding()]
param(
    [string]$RuntimeRoot = 'C:\Games\Final.Fantasy.VII.Remake.Intergrade-InsaneRamZes\End\Binaries\Win64',
    [string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path.TrimEnd('\')
$runtime = (Resolve-Path -LiteralPath $RuntimeRoot).Path.TrimEnd('\')
$shaderRoot = Join-Path $runtime 'ShaderFixes'
$modsRoot = Join-Path $runtime 'Mods'
$contactIniPath = Join-Path $modsRoot 'ContactShadows.ini'

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $stamp = [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss-fff')
    $OutputDirectory = Join-Path $repo "artifacts\runtime-toggle-audits\$stamp"
}
$output = [IO.Path]::GetFullPath($OutputDirectory).TrimEnd('\')
$allowedOutput = [IO.Path]::GetFullPath((Join-Path $repo 'artifacts\runtime-toggle-audits')).TrimEnd('\')
if (-not $output.StartsWith($allowedOutput + '\', [StringComparison]::OrdinalIgnoreCase)) {
    throw 'Output must remain below artifacts/runtime-toggle-audits.'
}
if (Test-Path -LiteralPath $output) { throw 'Output already exists; preserve the earlier audit.' }

$expected = [ordered]@{
    '08bb8764f1840179-cs.txt' = '08bb8764f1840179'
    '0e97888f9a8767da-cs.txt' = '0e97888f9a8767da'
    '5a9fbefe0ab6f815-cs.txt' = '5a9fbefe0ab6f815'
    '62b33a2d1e505241-cs.txt' = '62b33a2d1e505241'
    'c30cdc8365df9840-cs.txt' = 'c30cdc8365df9840'
}
$masterVariable = '$ue4fx_master_injected_v1'

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) { throw $Message }
}
function Get-IniSections([string]$Text) {
    $sections = @{}
    foreach ($match in [regex]::Matches($Text, '(?ms)^\s*\[(?<name>[^\]]+)\]\s*\r?\n(?<body>.*?)(?=^\s*\[|\z)')) {
        $sections[$match.Groups['name'].Value.Trim()] = $match.Groups['body'].Value
    }
    return $sections
}

Assert-True (Test-Path -LiteralPath $shaderRoot -PathType Container) "Missing ShaderFixes directory: $shaderRoot"
Assert-True (Test-Path -LiteralPath $modsRoot -PathType Container) "Missing Mods directory: $modsRoot"
Assert-True (Test-Path -LiteralPath $contactIniPath -PathType Leaf) "Missing ContactShadows.ini: $contactIniPath"

$activeShaders = @(Get-ChildItem -LiteralPath $shaderRoot -Recurse -File -Filter '*.txt' | Sort-Object FullName)
$activeNames = @($activeShaders | ForEach-Object Name)
Assert-True ($activeShaders.Count -eq $expected.Count) "Expected exactly $($expected.Count) active .txt replacements; found $($activeShaders.Count): $($activeNames -join ', ')"
foreach ($name in $expected.Keys) {
    Assert-True ($activeNames -ccontains $name) "Missing expected active replacement: $name"
}
foreach ($name in $activeNames) {
    Assert-True ($expected.Contains($name)) "Unexpected active replacement bypasses the approved set: $name"
}

$contactIni = Get-Content -LiteralPath $contactIniPath -Raw
$sections = Get-IniSections $contactIni
Assert-True ($contactIni -match '(?im)^\s*global\s+\$ue4fx_master_injected_v1\s*=\s*1\s*$') 'Page Down master variable must default ON.'
Assert-True (-not ($contactIni -match '(?i)VK_PRIOR|ue4fx_material1_contact_route|(?m)^\s*x28\s*=')) 'Page Up must be completely free when no experiment is active.'

$keySections = @($sections.Keys | Where-Object { $_ -match '^Key' })
Assert-True ($keySections.Count -eq 1) "Expected exactly one Page Down key section and no Page Up experiment; found: $($keySections -join ', ')"
$pageDown = $keySections | Where-Object { $sections[$_] -match '(?im)^\s*key\s*=\s*no_modifiers\s+VK_NEXT\s*$' }
Assert-True (@($pageDown).Count -eq 1) 'Expected one Page Down (VK_NEXT) key section.'
Assert-True ($sections[$pageDown] -match '(?im)^\s*\$ue4fx_master_injected_v1\s*=\s*0\s*,\s*1\s*$') 'Page Down must cycle only the master variable between 0 and 1.'

$overrideSections = @($sections.Keys | Where-Object { $_ -match '^ShaderOverrideUE4FXContact' })
Assert-True ($overrideSections.Count -eq $expected.Count) "Expected $($expected.Count) contact override sections; found $($overrideSections.Count)."

$records = @()
foreach ($file in $activeShaders) {
    $hash = $expected[$file.Name]
    $sectionName = $overrideSections | Where-Object { $sections[$_] -match "(?im)^\s*hash\s*=\s*$hash\s*$" }
    Assert-True (@($sectionName).Count -eq 1) "Expected one INI override for $($file.Name)."
    $body = $sections[$sectionName]
    Assert-True ($body -match '(?im)^\s*x31\s*=\s*\$ue4fx_master_injected_v1\s*$') "$($file.Name) is not bound to the Page Down master at x31."

    Assert-True (-not ($body -match '(?im)^\s*x28\s*=')) "$($file.Name) unexpectedly consumes the free Page Up experiment slot."

    $text = Get-Content -LiteralPath $file.FullName -Raw
    Assert-True ($text -match '(?s)^\s*//.*Generated by Microsoft \(R\) D3D Shader Disassembler.*using 3Dmigoto.*Input signature:.*Output signature:.*\r?\ncs_5_0\r?\n') "$($file.Name) is missing its authoritative original signature header."
    Assert-True ($text -match '(?im)^\s*dcl_resource_texture1d\s+\(float,float,float,float\)\s+t120\s*$') "$($file.Name) does not declare the 3Dmigoto parameter texture."
    Assert-True ($text -match '(?s)ld_indexable[^\r\n]*l\(31,\s*0,\s*0,\s*0\),\s*t120\.xyzw\s*\r?\n\s*eq[^\r\n]*l\(1\.000000\)\s*\r?\n\s*if_nz') "$($file.Name) does not guard its injected block with Page Down == 1."
    $hasExperimentLoad = $text -match 'l\(28,\s*0,\s*0,\s*0\),\s*t120\.xyzw'
    Assert-True (-not $hasExperimentLoad) "$($file.Name) still contains shader-side Page Up experiment code."

    $records += [ordered]@{
        file = $file.Name
        hash = $hash
        sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash
        masterIniBinding = 'x31'
        masterShaderLoad = 't120[31].x'
        pageUpExperiment = $false
    }
}

$otherIni = @(Get-ChildItem -LiteralPath $modsRoot -Recurse -File -Filter '*.ini' | Where-Object { $_.FullName -ne $contactIniPath })
foreach ($ini in $otherIni) {
    $text = Get-Content -LiteralPath $ini.FullName -Raw
    Assert-True (-not ($text -match '(?im)^\s*\[(Key|ShaderOverride)')) "Unexpected active key/override section outside ContactShadows.ini: $($ini.FullName)"
}

$logPath = Join-Path $runtime 'd3d11_log.txt'
$logEvidence = [ordered]@{ present = $false; lastSuccessfulExperimentReloadLine = $null }
if (Test-Path -LiteralPath $logPath -PathType Leaf) {
    $stream = [IO.File]::Open($logPath, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)
    try {
        $reader = [IO.StreamReader]::new($stream, [Text.Encoding]::UTF8, $true, 65536, $true)
        try { $log = $reader.ReadToEnd() } finally { $reader.Dispose() }
    } finally { $stream.Dispose() }
    $matches = [regex]::Matches($log, '(?im)^.*successfully reloaded shader:\s*62b33a2d1e505241-cs\.txt\s*$')
    $logEvidence.present = $true
    if ($matches.Count) { $logEvidence.lastSuccessfulExperimentReloadLine = $matches[$matches.Count - 1].Value.Trim() }
}

[IO.Directory]::CreateDirectory($output) | Out-Null
$manifest = [ordered]@{
    schemaVersion = 1
    generatedAtUtc = [DateTime]::UtcNow.ToString('o')
    result = 'passed'
    runtimeRoot = $runtime
    invariant = 'Every active injected replacement is gated by Page Down; Page Up is completely free until the next experiment.'
    master = [ordered]@{ key = 'Page Down'; virtualKey = 'VK_NEXT'; variable = $masterVariable; default = 1; shaderSlot = 't120[31].x' }
    experiment = $null
    activeShaders = $records
    otherActiveIniFiles = @($otherIni | ForEach-Object Name)
    logEvidence = $logEvidence
}
$utf8 = [Text.UTF8Encoding]::new($false)
$manifestPath = Join-Path $output 'manifest.json'
[IO.File]::WriteAllText($manifestPath, (($manifest | ConvertTo-Json -Depth 8) + "`n"), $utf8)

[pscustomobject]@{
    Result = 'passed'
    ActiveShaders = $activeShaders.Count
    PageDownGated = $records.Count
    PageUpShaders = @($records | Where-Object pageUpExperiment).Count
    Output = $manifestPath
    Sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $manifestPath).Hash
}
